### ISSUE TITLE
work from LAN, but from WAN not working

### ISSUE THREAD

**Issue by UltimatPronin** [ronggang/transmission-web-control#100]
From WAN only buttons shown. ((((

**Comment by marseneault** [comment]
Same for me.  Have been using version 0.6 for many years without issue.  Just updated to latest version today and the interface is empty when connected from WAN (no folders and no torrents show in the tables).  From LAN, everything shows up nicely.  I was able to roll back to version 1.0 (20141010) and everything works again.

**Comment by UltimatPronin** [comment]
By deleting cookies I resolved the issue.

**Comment by ronggang** [comment]
Hi @UltimatPronin ,you can try new version:
https://github.com/ronggang/transmission-web-control/blob/master/release/install-tr-control.sh

**Comment by UltimatPronin** [comment]
I jet tryed. After deleting cookies all is OK now.

**Comment by ronggang** [comment]
The new version has been deprecated cookies.

**Comment by marseneault** [comment]
New version confirmed working. Thank you!
