### ISSUE TITLE
Corrected translation for Portuguese Brazil

### ISSUE THREAD

**Issue by condector** [ronggang/transmission-web-control#102]
I saw a lot of words in Portuguese from Portugal inside the Portuguese Brazil translation and corrected that. I attached the zip file with the new pt-BR.js. This could help other Brazilian users from your software.

[pt-BR.js.zip](https://github.com/ronggang/transmission-web-control/files/1245427/pt-BR.js.zip)

**Comment by DarkAlexWang** [comment]
I have updated your corrections, thank for your contribution.
