### ISSUE TITLE
Add tracker

### ISSUE THREAD

**Issue by Leproide** [ronggang/transmission-web-control#105]
Hi,
Exist a way to add a list of tracker? I need this feature on my server.
In any case, nice work :D

**Comment by ronggang** [comment]
Hi, 
Do you mean this?
![inkedimg_2216_li](https://user-images.githubusercontent.com/8065899/31369405-cdd79158-adb6-11e7-889d-1deb6ca65f4f.jpg)

**Comment by Leproide** [comment]
Oh, i see now this :D 
But this allow me to add one tracker, is possible upload a file with multiple or have a large textbox for paste a long list of tracker?

**Comment by Leproide** [comment]
Hi :D 
I updated to the 1.4, this feature is in program?

**Comment by ronggang** [comment]
@Leproide 
may be released in the next version. 😄

**Comment by Leproide** [comment]
Tnx u so much :sparkling_heart:
