### ISSUE TITLE
新安装脚本说明

### ISSUE THREAD

**Issue by ronggang** [ronggang/transmission-web-control#106]
这几天整理了一下 `Tr Web Control` 的[安装脚本](https://github.com/ronggang/transmission-web-control/blob/master/release/install-tr-control.sh)，主要是增加了 `TRANSMISSION_WEB_HOME` 环境变量的支持，具体可参考[这个Wiki](https://github.com/ronggang/transmission-web-control/wiki/Transmission-Web-Interface-%E5%B7%A5%E4%BD%9C%E7%9B%AE%E5%BD%95)，如果没有其他异常，以后将正式启用这个脚本，希望各位有空时帮忙测试一下这个脚本，在此先谢过。

**由于本次没有更新原来的压缩包，所以原来的脚本不能获取到最新的代码，请使用新的[安装脚本](https://github.com/ronggang/transmission-web-control/blob/master/release/install-tr-control.sh)，或手工下载[压缩包](https://github.com/ronggang/transmission-web-control/raw/master/release/src.tar.gz)。**

同时新增了一个[关于Synology Download Station的说明](https://github.com/ronggang/transmission-web-control/wiki/%E5%85%B3%E4%BA%8E-Synology-Download-Station)，如有Synology产品的同学，也可帮忙测试一下，如有错误也可在此留言。

感谢各位的支持
栽培者 于 2017.10.15 晚

**Comment by fcying** [comment]
transmission通过systemd启动, 用方式2失败了(写/etc/profile 和当前用户的都不行)
在systemd脚本里面设置了环境变量后可以的
```
[Service]
Environment=TRANSMISSION_WEB_HOME=/volume1/tr-web-client
```

**Comment by ronggang** [comment]
@fcying 感谢反馈。

**Comment by ccdos** [comment]
关于 黑群晖，我使用 
 bash install-tr-control.sh
安装 一切正常， 

用  ds-control-easy-install.sh  反而无效
