### ISSUE TITLE
怎么更新新的代码？

### ISSUE THREAD

**Issue by ccdos** [ronggang/transmission-web-control#108]
刚刚发现有修正bug ，想重新安装一下，但是失败了

**Comment by ronggang** [comment]
请参考 #106 ；下载新的安装脚本，执行一下应该就可以了。

**Comment by cjj7227** [comment]
wget https://raw.githubusercontent.com/ronggang/transmission-web-control/master/release/install-tr-control.sh
sudo bash install-tr-control.sh

**Comment by ccdos** [comment]
谢谢， 今天 又试了下，成功了。

估计我上次网络问题
