### ISSUE TITLE
Web interface is empty

### ISSUE THREAD

**Issue by dudumaroja** [ronggang/transmission-web-control#109]
today i was installing the webui on my htpc, and for some odd reason when i use transmission-web-control interface nothing shows up, but the original interface work just fine. 

![Screenshot](https://user-images.githubusercontent.com/6276768/31802737-8bfca2b2-b52e-11e7-961d-5e7ab04e3f9d.JPG)

i dont know if it helps.. but i`m using libreelec 8.0.2 and Transmission version 2.92

any way to fix it?

**Comment by ronggang** [comment]
use the new install script:
```
wget https://github.com/ronggang/transmission-web-control/raw/master/release/install-tr-control.sh --no-check-certificate
sh install-tr-control.sh
```

**Comment by dudumaroja** [comment]
Thanks Ronggang.. this script worked.. but i had to manualy modify it to include the proper location to the transmission folder. ( it will not search for it ) 

it gave me this error

 

> MC:~ # sh install-tr-control.sh
> Searching Transmission Web Folder...
> Looking for folder: /usr/local/transmission/share/transmission/web
> Folder not found. Will search the entire /. This will take a while...
> ##############################################
> #
> # ERROR : Transmisson WEB UI Folder is missing.
> #
> ##############################################
> rm: can't remove 'src.tar.gz': No such file or directory


my transmission location is /storage/.kodi/addons/service.transmission

i had to put it in line 37 ROOT_FOLDER="/storage/.kodi/addons/service.transmission"
after i edited it worked and the web interface is working properly.. thank you
