### ISSUE TITLE
作者您好，针对群晖NAS问题

### ISSUE THREAD

**Issue by zfkira** [ronggang/transmission-web-control#110]
不知道是否可以做个 transmission_x86_64-xxxxxxx.spk 的安装包，这样可以直接从群晖套件内手动安装，毕竟通过winscp安装还是有些复杂。

**Comment by ronggang** [comment]
@zfkira 你好，目前不会制作安装包，其实用脚本安装，只有第一次使用ssh安装麻烦一点，后面更新可以在群晖里添加一个计划任务，不定期执行一下就可以了。

**Comment by zfkira** [comment]
谢谢作者的解答，我有两个小白问题想请教下
1.这两个命令在 wget https://github.com/ronggang/transmission-web-control/raw/master/release/ds-control-easy-install.sh 之后
sh ds-control-easy-install.sh
sudo bash ds-control-easy-install-en-http.sh
应该执行哪个？以上这两个命令区别在哪儿呢？
2.添加计划任务这块，添加什么呢？请教。谢谢！

**Comment by ronggang** [comment]
@zfkira 不知道你是安装了 Transmission，还是直接用的 Download Station？如果是安装了 Transmission，就不能使用你上面的那个脚本，那个是 Download Station 用的。

Transmission 安装脚本
https://github.com/ronggang/transmission-web-control/raw/master/release/tr-control-easy-install.sh

Download Station 安装脚本
https://github.com/ronggang/transmission-web-control/raw/master/release/ds-control-easy-install.sh

但没有你说的 ds-control-easy-install-en-http.sh 脚本。

具体 sh 和 bash 什么区别，你可以到网上搜索一下。

关于计划任务，你可以到群晖的【控制面板->计划任务】 里添加一个 “用户定义的脚本”，在【任务设置->用户定义的脚本】里输入脚本路径就可以了，比如 /volume1/home/tr-control-easy-install.sh，计划执行时间你自己定。

**Comment by zfkira** [comment]
哎哟。作者提醒我了。看来我装错了。我既安装了transmission 又安装了DS的安装脚本。这下我清楚了。谢谢作者的耐心指导。谢谢！

**Comment by zfkira** [comment]
作者你好，transmission 装好了。web ui 1.1, 之后试了你提到的计划任务并不起作用.请见下图，我在想是不是我要手动下载 tr-control-easy-install.sh 这个文件，然后在NAS卷一里面创建个文件夹，并将.sh 这个文件放进去，赋好权限，然后才能设置计划任务？
![2017-11-01_11-04-26](https://user-images.githubusercontent.com/22000271/32258265-878254be-bef4-11e7-854a-a2c3e4fb60d2.jpg)

**Comment by ronggang** [comment]
@zfkira 是的，我只是举了个例子，你根据自己的实际文件路径填写。
