### ISSUE TITLE
作者你好，一些关于您项目的问题

### ISSUE THREAD

**Issue by a1093773736** [ronggang/transmission-web-control#111]
原本transmission的web，替换你的后，无法添加种子任务，数据统计的也无法使用，现在只能看却不能添加。
![qq 20171030172015](https://user-images.githubusercontent.com/33219046/32163262-b590ad42-bd96-11e7-90a6-1d82f427de4a.png)
transmission版本2.92，系统lede。

**Comment by ronggang** [comment]
@a1093773736 你的web control版本太老了，请更新至最新版本，谢谢！

**Comment by a1093773736** [comment]
换了1.1已解决，谢谢了。
