### ISSUE TITLE
请问一下怎么卸载？

### ISSUE THREAD

**Issue by reechang** [ronggang/transmission-web-control#126]
有没有提供卸载脚本？
如果没有的话，应该怎么卸载？

**Comment by ronggang** [comment]
暂时没有卸载脚本，如果是通过脚本安装的，可以直接删除 `tr-web-control` 目录及 `index.html` `index.mobile.html` 文件；再把 `index.original.html` 改为 `index.html` 就可以了。
下次做一个卸载脚本吧。

**Comment by ronggang** [comment]
@reechang 新安装脚本已提供删除功能，如需要删除，请下载最新安装脚本，执行后按提示操作即可。
