### ISSUE TITLE
My errors

### ISSUE THREAD

**Issue by ewan34500** [ronggang/transmission-web-control#13]
I have found errors in your Transmission client , this is my interface : 
![capture du 2014-11-03 15 23 38](https://cloud.githubusercontent.com/assets/9164167/4884636/ad59245a-636d-11e4-9306-6261ebb32aa7.png)
I can't pause the torrents, or start too. 
in the left section, there are not the torrents active ... So many errors, I think it's because the client is old for the transmission version .... Can you fix that ?

**Comment by DarkAlexWang** [comment]
Seems like problem solved.
