### ISSUE TITLE
shift clicking on a checkbox should select all the other checkboxes between it

### ISSUE THREAD

**Issue by Scrxtchy** [ronggang/transmission-web-control#133]
Something which would be nice when coming over from rutorrent

could probably adapt it out of something like this
https://stackoverflow.com/questions/659508/how-can-i-shift-select-multiple-checkboxes-like-gmail

since jquery is already in use

**Comment by DarkAlexWang** [comment]
Reopen if needed, but close for now.

**Comment by andrasveto** [comment]
Is there no way to select multiple torrents at once in the webui?

**Comment by ronggang** [comment]
> Is there no way to select multiple torrents at once in the webui? If so, how are we meant to manage our torrents?

Just can't use the shift key.

**Comment by andrasveto** [comment]
Right. So how can we, for example, select 500 torrents that are in a certain folder and move them to another one if we can't shift select?

**Comment by Scrxtchy** [comment]
I use the drop down the select how many rows need to be displayed, click the select all on view button and then uncheck rows that need to be unchecked. It's a hassle if you aren't working on multiples of 10s/100s

**Comment by andrasveto** [comment]
If that's the solution, this should be reopened.

**Comment by ronggang** [comment]
The next version may consider supporting this feature.

**Comment by ted423** [comment]
试了下，失败了，只成功了一次，有什么技巧么

Tried it, failed, and only succeeded once. Any tips?

**Comment by ted423** [comment]
刷新了下页面好了，目前感觉是某些操作后导致该功能失效

Refreshed and it works. It seems that this function is invalid after some operations.
