### ISSUE TITLE
Reload and Auto Reload no longer working.

### ISSUE THREAD

**Issue by SX86** [ronggang/transmission-web-control#136]
As described in the title, the reload feature is not working for me. I have to switch between pages (All to Downloading, Downloading to All) for the view to refresh. This applies to all views.

Tried clearing cookies and cache, same issue.

Using Chrome 60 and 62, on TWC version: 1.4.0 (20171108)

**Comment by zfkira** [comment]
最近会有版本更新吗？

**Comment by SX86** [comment]
Google translates your answer to:
Will there be a version update recently?

If you are asking if it was updated recently, then no, the current build is the first and last I installed.

**Comment by balonik** [comment]
Hopefully I was able to reproduce the issue you are having.
Please try to
- edit the index.html and change the 'system.min.js' to 'system.js'
- edit the 'src/tr-web-control/script/system.js' and change line 1339 from '}' to 'system.resetTorrentInfos(oldInfos);}'

Please let me know if that fixed it.

**Comment by SX86** [comment]
With further testing, and without applying the fix given to be in the previous comment, I discovered that the auto refresh bug is only present when accessing the Transmission Web Control page using HTTPS (with a self signed certificate) instead of HTTP. I'm not sure if this behavior is expected, but I'm sure I've seen it work before over HTTPS, but I may be wrong.

**Comment by balonik** [comment]
AFAIK Transmission itself does not provide HTTPS connection and the Web is served only by HTTP. Are you using proxy to get it over HTTPS?

**Comment by SX86** [comment]
Yes, I'm using reverse proxy on my Synology DiskStation. That way I can set any HTTP-only services to be served over HTTPS, externally.

**Comment by SX86** [comment]
I got rid of my self-signed certificate, and got a valid certificate instead. I now have 1.5.0 beta installed, and auto refresh seems to be working well, now! I don't know if the issue was caused by the self-signed certificate, but that issue is now resolved for me. You may close it, if you want.
