### ISSUE TITLE
Update problem..... 

### ISSUE THREAD

**Issue by IkaSGC** [ronggang/transmission-web-control#142]
Hi, simple question, how to update to new version 1.4.1 ??? I make the simple install script but still have 1.4.0....

**Comment by sagatxxx** [comment]
same problem here
Description: Debian GNU/Linux 7 (wheezy)
Release: 7.11
Codename: wheezy

**Comment by sagatxxx** [comment]
ready resolved!

in my case the installation directory is: ROOT_FOLDER = "/ usr / local / share / transmission"
I changed it in the installation script and ready! everything resolved!!

**Comment by lzcykevin** [comment]
cd /usr/local/share/transmission/web
rm -rf ./*
wget https://github.com/ronggang/transmission-web-control/releases/download/v1.4.1/src.tar.gz
unzip src.tar.gz 
finished

**Comment by ronggang** [comment]
@IkaSGC See: https://github.com/ronggang/transmission-web-control/wiki/Linux-Installation
