### ISSUE TITLE
Help ME. broken web Ui.

### ISSUE THREAD

**Issue by antonioshim** [ronggang/transmission-web-control#144]
Hello and Thanks to your Project.

But, My web ui is Broken.

Plz, Help Me.

![cap 2018-02-15 01-50-11-533](https://user-images.githubusercontent.com/36483585/36216699-dd2d37ac-11f2-11e8-8bb3-89754f08c687.png)
![cap 2018-02-15 01-51-13-015](https://user-images.githubusercontent.com/36483585/36216701-dd581ef4-11f2-11e8-9091-473fe2a4f451.png)
![cap 2018-02-15 01-51-55-050](https://user-images.githubusercontent.com/36483585/36216702-dd7eb4e2-11f2-11e8-8df2-b7c6326c8ecd.png)

**Comment by harveyconnor** [comment]
same issue here
`
gzip: tar: favicon.ico: Cannot write: No space left on device
tar: index.html: Cannot write: No space left on device
stdin: unexpected end of file
tar: index.mobile.html: Cannot write: No space left on device
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Transmission Web Control Installation completed!
`

**Comment by darkon5** [comment]
@harveyconnor do a ``df -h`` to check if you have space available to install this. If you do, perform the installation with sudo.

**Comment by Monter** [comment]
@antonioshim  - all folders in this version have incorrect rights (rw- rw- rw- instead of rwx r-x r-x)

**Comment by lzcykevin** [comment]
I think that is permission problems.
u can use this command in your bash, maybe can solve ur problem

chmod 755 -R /usr/share/transmission/web/

**Comment by Alraemon** [comment]
@lzcykevin  thanks, that is exactly where the problem is.

**Comment by Monter** [comment]
It seems to me that this problem has already been solved and this issue can be closed.
