### ISSUE TITLE
批量添加Tracker不会自动删除空行

### ISSUE THREAD

**Issue by Tony-1998** [ronggang/transmission-web-control#146]
希望添加自动删空行和去重，这样直接复制列表就很方便了

**Comment by ronggang** [comment]
空行应该是不会添加的，去重功能下次更新时加上。

**Comment by Tony-1998** [comment]
我在复制下面这份列表的时候添加了几百个空的trackers，难道是我添加姿势不对吗吗？
https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt

**Comment by ronggang** [comment]
@Tony-1998 你用的是什么浏览器？可否提供一下详细信息。刚刚用 Chrome 64.0.3282.140 试了下你这个列表，不会添加空行。

**Comment by Tony-1998** [comment]
Chrome 63.0.3239.132

**Comment by Tony-1998** [comment]
我又测试了一次，还是会添加几百个空的tracker，整整17页

**Comment by ronggang** [comment]
@Tony-1998 刚刚看了一下，添加的代码没问题，显示的时候原来的代码有BUG。😵
