### ISSUE TITLE
Align this icons, update the easyui ... 

### ISSUE THREAD

**Issue by ewan34500** [ronggang/transmission-web-control#15]
I know we can align this icon, so can you update the file easyui.js , because when I change the theme, I obtain a bad result essentialy in the menu ...
![capture du 2014-11-05 10 04 33](https://cloud.githubusercontent.com/assets/9164167/4915074/5041ddf2-64cb-11e4-85e8-fedf7568ed71.png)

**Comment by DarkAlexWang** [comment]
Can you check if the problem remains after the new update #46?
Right now, I will close this issue.
Please reopen if you think it is necessary.
