### ISSUE TITLE
选择非当前页面的任务A，如果不手动取消， 去操作当前页面的B任务，会导致A任务被误操作

### ISSUE THREAD

**Issue by fengchen8611** [ronggang/transmission-web-control#152]
在做种界面浏览时选择一个A任务，然后换到其他界面操作B任务时，不能自动取消A任务选择，会导致A可能会被误操作（比如：点开做种的A任务，查看A任务的种子属性，未手动取消A任务的选择，然后去删除、暂停其他页面（效验、下载等）的B种子，会造成A种子也会被删除、暂停，希望能切换页面时能自动取消非当前页面的选择或者出现提醒：当前是操作哪几个任务

**Comment by shNanChen** [comment]
我这次换机器，还原做种任务时也碰到这个问题，
先前选中的任务，在切换“数据目录”后，在后台一直会保持选中，
确实容易误操作






在 2018年3月7日 上午11:24，fengchen8611 <notifications@github.com>写道：

**Comment by shNanChen** [comment]
搞定了吗？怎么我试了下，还是没有取消选中，
我更换后清空了浏览器缓存，
看看别的人反馈吧，我搞不太来
