### ISSUE TITLE
Question and request

### ISSUE THREAD

**Issue by Monter** [ronggang/transmission-web-control#153]
Question: why change icons? The new ones are terrible ...

Request: stop linking to external sites (CSS)

**Comment by ronggang** [comment]
@Monter , Thanks for feedback.
1. I'm trying new ways to better adapt the themes on the icon issue.
2. Now for the beta, the official version will enable internal links.

**Comment by Monter** [comment]
Old icons are fine and do not spoil the appearance of skins.
However, the Trackers section in the tree on the left has stopped working...

**Comment by ronggang** [comment]
Because BT Trackers is set to hide by default.
The next version will increase the parameter can be set.

**Comment by cry0xen** [comment]
Actually I like the new Icons better than old ones. But the new ones have problems too.

1. they are not enough eye catchy.
2, Error and checking, specially error is not good or better to say not suitable.

its really nice you are changing icons specially experimenting with new ones. I believe old icons were not  good enough.

**Comment by Monter** [comment]
@ronggang : Trackers list menu in tree on the left does not work even if the display setting (showBTServers) is changed to true.

**Comment by ronggang** [comment]
@cry0xen Those icons are really not very recognizable, I am trying new ' icon font ' icon, if you have good icons, please recommend. :pray:

@Monter Because local stored parameters are preferred, Config.json file parameters are overwritten, you can either empty the local store and try again, or wait for the update to be released.  :smile:

**Comment by cry0xen** [comment]
@ronggang torrenting has an established perception. for example, interface like utorrent 2.2.1 . thats why I have converted to transmission remote gui and yours. I think icon fonts wont be good for your application. Any way I will look for free open source icon that suites the need.

[Offtopic] Lastly, I submitted an en language update... I dont know how to receive github. did you guys receive it?

**Comment by DarkAlexWang** [comment]
@cry0xen Did you submit as PR? I did not see your update.

**Comment by cry0xen** [comment]
@DarkAlexWang dont know. here 
[en.zip](https://github.com/ronggang/transmission-web-control/files/1817683/en.zip)
