### ISSUE TITLE
Width of the "Config" window

### ISSUE THREAD

**Issue by vodek3** [ronggang/transmission-web-control#158]
![twc-scheduler](https://user-images.githubusercontent.com/25941601/37460535-8722b582-285c-11e8-9609-9d0ae460c593.jpg)
Width of the "Config" window it is not enough to write the days of the week in Russian without abbreviations.
A little bit wider, it would be great!

**Comment by ronggang** [comment]
Thanks for feedback, will be improved at the next release.

**Comment by vodek3** [comment]
Great!
