### ISSUE TITLE
Right click menu item "Open containing folder"

### ISSUE THREAD

**Issue by vodek3** [ronggang/transmission-web-control#160]
It would be very convenient to add the right click menu item "Open the torrent containing folder".
This is not enough!

http://i1.sendpic.org/i/jy/jyTZxKiZikcTiWfbfP2VIduWWdj.jpg

**Comment by ronggang** [comment]
Sorry, WebUI don't have permission to do this.

**Comment by vodek3** [comment]
It's clear

**Comment by byrain** [comment]
@ronggang I just wondering is it possible to add a "copy folder path to clipboard" to right click menu?
Thx 

BTW, I contribute the 600th star :)

**Comment by ronggang** [comment]
@byrain Congratulations :)
"copy folder path to clipboard" this feature should be implemented.

**Comment by Monter** [comment]
It seems to me that this problem has already been solved and this issue can be closed.
