### ISSUE TITLE
增加界面状态记忆功能是什么样子的？

### ISSUE THREAD

**Issue by kokpk** [ronggang/transmission-web-control#163]
请问增加界面状态记忆功能是什么样子的？取消“自动显示种子属性”功能话 我怎么才能看到种子属性里的参数？

**Comment by kokpk** [comment]
已经发现谢谢

**Comment by Unlash** [comment]
请问在那个地方。

**Comment by ronggang** [comment]
@Unlash 已改为自动记忆，只要点一次展开属性栏，下次就一记住了

**Comment by Unlash** [comment]
@ronggang 请问下。手动安装，我的环境是debian9.我下载transmission-web-control.1.5.1.zip，解压。替换到/usr/share/transmission/web/ 下面。在重启transmission就可以吗？

**Comment by ronggang** [comment]
@Unlash 不用重启，刷新一下就可以了。

**Comment by Unlash** [comment]
@ronggang 好的谢谢。
