### ISSUE TITLE
每次刷新都不显示种子列表

### ISSUE THREAD

**Issue by cjj7227** [ronggang/transmission-web-control#165]
1.5.1版
![image](https://user-images.githubusercontent.com/29445518/38041660-f032d34e-32e4-11e8-95df-35380852a1a8.png)
每次都要手动点一下全部才显示全部种子。

**Comment by ronggang** [comment]
谢谢反馈。

**Comment by ronggang** [comment]
@cjj7227 已修复，请重新执行安装脚本即可。
