### ISSUE TITLE
v1.5.1版本显示剩余时间为秒数

### ISSUE THREAD

**Issue by cc5771027** [ronggang/transmission-web-control#168]
![img](https://i.imgur.com/QgG1d2n.png)

**Comment by ronggang** [comment]
请强制刷新你的浏览器缓存。

**Comment by Mosney** [comment]
@ronggang 强制刷新依然无效

**Comment by thomasho18** [comment]
我也遇到同樣問題，強制刷新了也是一樣...

**Comment by Mosney** [comment]
我清除浏览器数据搞定，隐身标签也是正常的，可是强制刷新并不能解决问题

**Comment by thomasho18** [comment]
我使用Firefox 59.0.2，我刪除了"已快取的內容"和"cookie"，還是顯示秒數.......

**Comment by cjj7227** [comment]
我也是秒。

**Comment by ronggang** [comment]
的确是个BUG，对于本地有配置的同学，可能会显示为秒，如果要显示正常可以尝试以下方法：
1、按F12打开开发者工具；
2、切换到 Console 选项卡，然后分别执行以下语句：
```js
delete system.userConfig.torrentList.fields
```
```js
system.saveUserConfig()
```
3、执行完后，会清除用户定义的显示列信息，恢复为默认状态；
4、刷新浏览器页面就可以正常显示了；

不过这只是临时的解决方法，如果不急的同学可以等等，我会重新打包一个已修复的安装包，重新安装一次即可。
