### ISSUE TITLE
Bug : Copy download location to clipboard does not work

### ISSUE THREAD

**Issue by cry0xen** [ronggang/transmission-web-control#171]
Version 1.5.1-update-1

**Bug Report:** The newly added feature "Copy download location to clipboard" does nothing.
**Additional Improvement:** Please add an icon in Base>Download Dir as shortcut for this feature. It will improve UI experience.

**Note** I think its high time that we should start posting issues in english here so people all around the world can understand that. This will help you a lot specially making the discussion accessible to people making them interested.

**Comment by ronggang** [comment]
@cry0xen Thanks for feedback and for your suggestions.
They are probably considering my English level generally, so take care of me, :)
