### ISSUE TITLE
更新了1.5.1 update1，种子列表变空白了~~

### ISSUE THREAD

**Issue by lottelucky** [ronggang/transmission-web-control#172]
Transmssion 版本: 2.93
Tr Web Control 版本：1.5.1 update1
浏览器名称及版本： CHROME 65.0.3325.181（正式版本） （64 位）
问题描述: 种子列表变空白了，如下图
![image](https://user-images.githubusercontent.com/28852260/38120004-5633293c-33f8-11e8-89d8-c87df1bb6bbd.png)

如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 
* Tr Web Control 版本 
* 浏览器名称及版本：
* 问题描述:
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by lottelucky** [comment]
2018-03-30 9:22 GMT+08:00 栽培者 <notifications@github.com>:

**Comment by lottelucky** [comment]
![image](https://user-images.githubusercontent.com/28852260/38121415-894f59a4-3401-11e8-8178-be0a30cc59ff.png)
![image](https://user-images.githubusercontent.com/28852260/38121422-95a6ce58-3401-11e8-81f4-19b8557980bb.png)

**Comment by ronggang** [comment]
@lottelucky 你截图上暴露密码了，给你先删除了。

**Comment by ronggang** [comment]
@lottelucky 更新到 1.5.1-update-2 试一下。

**Comment by lottelucky** [comment]
更新到update2，还是不正常！
奇怪了~~
在没有更新到update1时， 都正常
今天更新到update1后，种子列表就出不来了
我又尝试退回到1.5.1甚至1.5.0beta，种子列表也出不来~~
另：WIN10自带的Edge是正常的~

2018-03-30 14:44 GMT+08:00 栽培者 <notifications@github.com>:

**Comment by lottelucky** [comment]
我刚刚尝试把chrome的Cookies清除后，打开正常了。

在 2018年3月30日 下午3:14，非凡的小剑 <lottelucky@gmail.com>写道：
