### ISSUE TITLE
“数据目录”选项无法真正关闭

### ISSUE THREAD

**Issue by lottelucky** [ronggang/transmission-web-control#177]
Transmssion 版本: 2.93
Tr Web Control 版本：1.5.1 update2
浏览器名称及版本： CHROME 65.0.3325.181（正式版本） （64 位）
问题描述:“数据目录”选项无法真正关闭
1、手动关闭“数据目录”
![image](https://user-images.githubusercontent.com/28852260/38159653-7d06a7f4-34df-11e8-92e8-1fb352d9af84.png)
2、然后再刷新网页，“数据目录”的选择框是“未选”状态，而下方却出现了
![image](https://user-images.githubusercontent.com/28852260/38159661-b2816e14-34df-11e8-8079-1af49298b8fd.png)

**Comment by Monter** [comment]
In English: although the "Folders" option is not marked, this item appears in the list in the left column. Hiding is possible by checking and unchecking the "Folders" option.
