### ISSUE TITLE
Dont open Trackers tree by default

### ISSUE THREAD

**Issue by sandrotosi** [ronggang/transmission-web-control#19]
Transmission Version:2.84 (14307), RPC: 15, WEB Control: 0.6 Beta(20130913) [as avail on qnap nas]

when loading the page (new ui) the Trackers tree is opened by default, which is unnecessary and slows down the page loading

please disable it by default or add an option to do that

**Comment by sandrotosi** [comment]
this still applies to WEB Control: 1.0 Beta(20141010)

**Comment by DarkAlexWang** [comment]
#46 Fixed by balonik.
