### ISSUE TITLE
src.tar.gz 文件 404 了

### ISSUE THREAD

**Issue by ccdos** [ronggang/transmission-web-control#196]
最新版提示后，安装遇到 404 错误
这个文件下载不到
https://github.com/ronggang/transmission-web-control/raw/master/release/src.tar.gz 
====================

root@NAS_T2900V_2:~# bash install-tr-control.sh
Searching Transmission Web Folder...
Looking for folder: /usr/local/transmission/share/transmission/web
Folder found. Using it.
Downloading Transmission Web Control...
--2018-04-03 15:23:12--  https://github.com/ronggang/transmission-web-control/raw/master/release/src.tar.gz
Resolving github.com... 13.250.177.223, 13.229.188.59, 52.74.223.119
Connecting to github.com|13.250.177.223|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-04-03 15:23:30 ERROR 404: Not Found.

Installing...
tar (child): src.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Transmission Web Control Installation completed!
rm: cannot remove ‘src.tar.gz’: No such file or directory

**Comment by ronggang** [comment]
重新下载安装脚本
https://github.com/ronggang/transmission-web-control/wiki/Linux-Installation-CN
