### ISSUE TITLE
更新UI图标消失

### ISSUE THREAD

**Issue by lihansunbai** [ronggang/transmission-web-control#198]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本:  2.84(PRC 15)
* Tr Web Control 版本: 1.5.1update-2
* 浏览器名称及版本：Chrome Version 65.0.3325.181 (Official Build) (64-bit)
* 问题描述:
更新1.5.1update2之后，页面工具栏的UI图标都消失了，但是操作可以正常进行。
清除缓存和强制刷新都没有作用？
卸载和清空后再次安装也没有解决问题。
请求帮助～
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by ronggang** [comment]
@lihansunbai 请按F12，切换至 Console 选项卡，然后按Ctrl+F5刷新，再截个图上传一下，谢谢。

**Comment by lihansunbai** [comment]
谢谢dalao回复。
查了一下console，发现所有资源都404了，应该是权限不对，改了权限就好了。
不知道是不是个BUG之类的。如果不需要进一步关注的话，可以close了～

**Comment by ronggang** [comment]
如果是通过脚本安装的，权限应该会自动设置。
如果是手工安装的，需要自己调整权限。
那我先关闭了。
