### ISSUE TITLE
Tr Web Control界面语言自动变为英文

### ISSUE THREAD

**Issue by pigpigabc123** [ronggang/transmission-web-control#199]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本:  2.93 (3c5870d4f5), RPC: 15
* Tr Web Control 版本: 1.5.1 update-2 (20180330)
* 浏览器名称及版本：chrome
* 问题描述:
打开Tr Web Control界面语言自动变为英文，设置中文后关闭浏览器重新打开后自动变为英文。老版本无此问题。
--------------------
## For English User 
Please provide the following information.
* Transmssion version:  2.93 (3c5870d4f5), RPC: 15
* Tr Web Control version: 1.5.1 update-2 (20180330)
* Browser name & version：chrome
* Problem description:

**Comment by ronggang** [comment]
@pigpigabc123 
1、不知道你说的老版本是哪个版本？
2、你的浏览器默认是英文吗？
3、其他设置会恢复成默认的吗？比如说，调整了列表的排序和列的位置。

**Comment by pigpigabc123** [comment]
已解决，浏览器默认语言问题。
