### ISSUE TITLE
Remaining time sometimes shows "%ss" as seconds

### ISSUE THREAD

**Issue by sandrotosi** [ronggang/transmission-web-control#20]
Transmission Version:2.84 (14307), RPC: 15, WEB Control: 0.6 Beta(20130913) [as avail on qnap nas]

I think it is when the seconds are 0, but sometimes in the Remaining column you can see "16m %ss" (16 is made up, it's just a number)

**Comment by sandrotosi** [comment]
this is still happening with "WEB Control: 1.0 Beta(20141010)"

**Comment by DarkAlexWang** [comment]
#46 Fixed by balonik
