### ISSUE TITLE
How to update Tr Web Control on xiaomi router, model: Mi 3G

### ISSUE THREAD

**Issue by lordmathbr** [ronggang/transmission-web-control#204]
Hi friends, sorry my english, (brazilian)

how to update Tr Web 1.0 to recent version??

I'm following the tutorial, but I'm having this error..

**BusyBox v1.24.2 (2018-04-08 01:25:59 MSK) built-in shell (ash)
Enter 'help' for a list of built-in commands.**

**/home/root # ls**
install-tr-control.sh  
src.tar.gz

**/home/root # sudo bash install-tr-control.sh**
-sh: sudo: not found

**/home/root # bash install-tr-control.sh**
install-tr-control.sh: line 7: syntax error: unexpected newline

**/home/root # ./install-tr-control.sh**
-sh: ./install-tr-control.sh: Permission denied

**Comment by Monter** [comment]
I don't know this device but after downloading the installation script maybe you should first give it the right to run: `chmod + x install-tr-control.sh`
Do you have OPKG installed at all?

**Comment by ronggang** [comment]
@lordmathbr 
I am not sure which version of the script you are using, please update to the latest version and try again.
```
rm install-tr-control.sh
wget https://raw.githubusercontent.com/ronggang/transmission-web-control/master/release/install-tr-control.sh
bash install-tr-control.sh
```

**Comment by DarkAlexWang** [comment]
Reopen if needed, but close for now.
