### ISSUE TITLE
Remaining time column sort lexicographically instead of using time sorting

### ISSUE THREAD

**Issue by sandrotosi** [ronggang/transmission-web-control#21]
Transmission Version:2.84 (14307), RPC: 15, WEB Control: 0.6 Beta(20130913) [as avail on qnap nas]

this is an example of the ordering when sorting on the remaining time column (real data, just exstracted):

12h 58m 1s
13m 4s
14d 3h 48m 48s
15h 41m 37s

that means instead of sorting on time (like the number of seconds) it sorts lexicographically, (so 12h is lower than 13m because 2 < 3), which is not the correct ordering you want

**Comment by sandrotosi** [comment]
the same still applies for "WEB Control: 1.0 Beta(20141010)"

**Comment by DarkAlexWang** [comment]
#46 Fixed by balonik.
