### ISSUE TITLE
1.6.0 label window is too small

### ISSUE THREAD

**Issue by Monter** [ronggang/transmission-web-control#219]
* Tr Web Control version: 1.6.0 alpha (20180418)
* Browser name & version：latest Chromium
* Problem description: Custom label adding window is too small, see screen:

![tr_control_labels](https://user-images.githubusercontent.com/9859492/38943394-9466ccac-4331-11e8-905d-59e1491aeac1.png)

**Comment by ronggang** [comment]
@Monter Looks like a style problem. I'll find out what caused it.

This is mine:

![tim 20180419081916](https://user-images.githubusercontent.com/8065899/38964641-77fdcff6-43aa-11e8-9398-7c2a04c147ae.png)

**Comment by DarkAlexWang** [comment]
Close for inactivity.
