### ISSUE TITLE
Some configurations are not saved in settings.json when set by the UI

### ISSUE THREAD

**Issue by sandrotosi** [ronggang/transmission-web-control#22]
Transmission Version:2.84 (14307), RPC: 15, WEB Control: 0.6 Beta(20130913) [as avail on qnap nas]

like:
- 'Limit > Max global upload speed' enabled and its value
- the value of 'Limit > Whether or not to consider idle torrents as stalled'

maybe other Im not aware of

**Comment by DarkAlexWang** [comment]
I dont see this problem now. Please check the recent update.

**Comment by sandrotosi** [comment]
the bug is still there: I just changed the download size to 301, saved, but in settings.json theres still:

```
    "download-queue-size": 300,
```

same for the exact same issue reported in the original message: 'Limit > Max global upload speed' enabled and its value

**Comment by balonik** [comment]
@sandrotosi 
web interface sets the "running" value. if you refresh the page (F5) it reloads all the settings from running transmission daemon so you can confirm that the limit is set properly.
transmission does not update the settings.json immediately. settings.json are updated only during daemon normal shutdown. if you want to make sure that the setting is applied on next startup, stop and start transmission daemon after you edit the values in web gui.
if you edit settings.json manually while transmission is running, you changes will be overwritten by transmission on next daemon shutdown.
