### ISSUE TITLE
Swapped hints for buttons

### ISSUE THREAD

**Issue by Monter** [ronggang/transmission-web-control#222]
Swapped hints for button-allow and button-deny buttons (language and translation files are OK, the problem is in the core), so the green file acceptance icon has the description "Skip checked file (s)" and the red file for the given reject file is described as "Download checked file (s)".

**Comment by Monter** [comment]
I meant that the functions of the green and red buttons are replaced (files tab in torrent descripttion, column "Wanted"). The red one is to cancel the download of the selected file and this is what it does, but the hint over it describes the inverse function. The same is with the green button.

![tr_replaced_hints](https://user-images.githubusercontent.com/9859492/38977914-0ea83210-43b6-11e8-8a1b-27bd14337cc3.png)

**Comment by ronggang** [comment]
Is my mistake.
