### ISSUE TITLE
Sort by queue number

### ISSUE THREAD

**Issue by oilervoss** [ronggang/transmission-web-control#223]
The Queue column cannot be sorted. I don't know if it's only with me.

I'm sorry if there is something opened in Japanese. I didn't find it.

--------------------
* Transmission:  2.92+git-4 running on OpenWRT
* Tr Web Control: 1.5.1 update 2 but probably since 1.4.0
* Browser name & version：Last Chrome, Last Edge

**Comment by oilervoss** [comment]
I really miss that function. 
Here, the ISP's habitually are slow and for sure congested so we need to limit our active downloads to few torrents and let them work overnight. I usually get a bunch of magnets in Transmission (thanks to  TWC) and then queue them according to my priorities. For such, I am forced to use another Transmission web interface since TWC lacks it.

I'd like to suggest it as a future improvement.

**Comment by oilervoss** [comment]
@ronggang Superb! I got it.
I had some issues with the script in my particular system (Openwrt @ TPLink WDR4300) but I could manage them. Nothing worth to patch. Thank you very much.

**Comment by yeahman45** [comment]
I installed from master repo and I still cannot sort by "Queue"
