### ISSUE TITLE
v1.6.0-alpha 左侧导航栏 数据目录 显示不出 具体路径

### ISSUE THREAD

**Issue by fancygg802** [ronggang/transmission-web-control#224]
* Transmssion 版本: Transmission: 2.93
* Tr Web Control 版本: 1.6.0 alpha (20180418)
* 浏览器名称及版本：chrome 65
* 问题描述:左侧导航栏 数据目录下面显示不出具体的数据的路径，上个版本还是正常的~~

**Comment by ronggang** [comment]
请参考 https://github.com/ronggang/transmission-web-control/wiki/QA-CN
