### ISSUE TITLE
1.6.0 alpha (20180418) - dark theme numbers too "grey"

### ISSUE THREAD

**Issue by sandrotosi** [ronggang/transmission-web-control#228]
![dark_theme](https://user-images.githubusercontent.com/346648/39088054-b2a7efe4-4579-11e8-9e1d-71904ac3217e.png)
just pulled the latest HEAD (9ab9ad2) and the colors for the numbers in the dark theme (Base > Black) are too "grey" and hard to read. with the previous commit i was using (fefe176) they were easier to read

can you have a look?

thanks!

**Comment by sandrotosi** [comment]
thanks, much better!

**Comment by Monter** [comment]
Hmmm, this has not been repaired here? https://github.com/ronggang/transmission-web-control/pull/218/commits/4f0ff607b4409dbc101ca8a36d38c353c5616276

**Comment by sandrotosi** [comment]
oh yes it has been fixed, and i was thanking u :)

**Comment by ronggang** [comment]
@Monter It's my fault. Because I adjusted the loading order of the style files.
