### ISSUE TITLE
Sometimes start/stop/cancel icons are shown as disabled

### ISSUE THREAD

**Issue by sandrotosi** [ronggang/transmission-web-control#23]
Transmission Version:2.84 (14307), RPC: 15, WEB Control: 0.6 Beta(20130913) [as avail on qnap nas]

with some torrents selected, sometime the start/stop/cancel icons are shown as disabled but clicking on them they perform the requsted operations

**Comment by sandrotosi** [comment]
this still applies to WEB Control: 1.0 Beta(20141010) - another case is the move to the top/bottom of the queue

**Comment by DarkAlexWang** [comment]
#46 - Fixed by balonik
