### ISSUE TITLE
按钮注释错误：当前种子属性-文件-绿色对勾和红色叉号按钮的注释错误

### ISSUE THREAD

**Issue by Mosney** [ronggang/transmission-web-control#230]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.93
* Tr Web Control 版本: 1.6.0alpha
* 浏览器名称及版本：centbrowser  3.2.4.23（正式版本） （64 位） (Chromium 64.0.3282.140)
* 问题描述: 
![image](https://user-images.githubusercontent.com/22477230/39234133-fc136432-48a4-11e8-85c4-fe072bc1961d.png)
如图所示两个按钮的注释弄反了

--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by Monter** [comment]
Repaired here: https://github.com/ronggang/transmission-web-control/issues/222
Before adding a new issue, please always check the latest version.

**Comment by Mosney** [comment]
@Monter Yeah, of course I know what it means , but in my screenshot, green button say: ignore selected file, red button say: download selected file. I think it is wrong. Like what you say, "The green button is to allow downloading the indicated file, red to cancel the download", this is correct.

**Comment by Monter** [comment]
@Mosney : hit "Clone or download" button and click "Download ZIP" - this ensures the download of the latest version with the corrected issue #222 
The official release in releases section may not contain the latest patches.
Can you download the latest code and check again?

**Comment by Rhilip** [comment]
This problem fixed in commit https://github.com/ronggang/transmission-web-control/commit/9ab9ad22b0373436875ebb04e0c11eecc7d8eb7a 
But the offical release didn't contain this patch.

```bash
wget https://github.com/ronggang/transmission-web-control/archive/v1.6.0-alpha.tar.gz
tar -zxf v1.6.0-alpha.tar.gz
cd transmission-web-control-1.6.0-alpha/
sed -n '246,258p' src/tr-web-control/template/torrent-attribute.html
```

and you will see
```
					id:"pager-button-allow",
					iconCls:'icon-allow',
					title: system.lang.torrent.attribute["tip"]["button-deny"],
					handler:function(){
						changeSelectedFilesWanted(true,$(this));
					}
				},'-',{
					id:"pager-button-deny",
					iconCls:'icon-deny',
					title: system.lang.torrent.attribute["tip"]["button-allow"],
					handler:function(){
						changeSelectedFilesWanted(false,$(this));
					}
```

**Comment by Mosney** [comment]
@Monter @Rhilip OK got it. But I'd like use release version, clone all repo may not stable version in most of the time .

**Comment by ronggang** [comment]
是的，之前的确存在这个问题，更新至最新代码可以解决；使用最新的安装脚本，选择9即可安装最新的代码
![](https://user-images.githubusercontent.com/8065899/39025828-1f1bd2c0-447c-11e8-8d3d-b43b395952b8.png)
