### ISSUE TITLE
当前页面显示种子数无法保存

### ISSUE THREAD

**Issue by chiting0824** [ronggang/transmission-web-control#232]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.93
* Tr Web Control 版本: 1.5.1 updata-2
* 浏览器名称及版本：chrome
* 问题描述：当前页面种子数默认是30，当设置成其他数值后重新登入又变回了30，无法保存其他数值。
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by ronggang** [comment]
see #211
