### ISSUE TITLE
用户标签用不了

### ISSUE THREAD

**Issue by SuTree** [ronggang/transmission-web-control#234]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.92
* Tr Web Control 版本: 1.60 a
* 浏览器名称及版本：chrome  66.0.3359.117 及firefox 59.0.2
* 问题描述: 用户标签用不了 ，编辑保存后没有，颜色也无法选，要自己找颜色代码？
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by ronggang** [comment]
不能保存的问题会在下次发布时修复。
颜色选择，会择机加入。

**Comment by SuTree** [comment]
收到，感谢
