### ISSUE TITLE
校检进度不显示

### ISSUE THREAD

**Issue by Mosney** [ronggang/transmission-web-control#235]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。

- Transmssion版本: 2.93
- Tr Web Control 版本: 1.6.0alpha
- 浏览器名称及版本：CentBrowser 3.2.4.23（正式版本） （64 位） (Chromium 64.0.3282.140)
- 问题描述: 

> ![image](https://user-images.githubusercontent.com/22477230/39298602-3d26db00-4979-11e8-849e-5ea76078c63c.png)

### 如图所示，校检进度一直显示为0，实际进度使用 [Transmission Remote GUI](https://github.com/transmission-remote-gui/transgui/) 能看到。
update：似乎只有这个种子的校检进度有问题，其他种子校检进度正常显示，我再观察一段时间吧。

**Comment by Rhilip** [comment]
请确认你的Web-Control是否刷新正常以及与Remote GUI的刷新间隔相同。
另请说明是否该种子在完全校验结束后能正常切换到做种或完成状态

**Comment by Mosney** [comment]
@Rhilip 我当然都刷新过了并且特地使用无痕标签来测试的 校检完成后是可以继续的 所以我说是显示进度不正常

**Comment by ronggang** [comment]
@Mosney 如果可以，请在浏览器中打开开发者工具，查看是否有错误信息。

**Comment by Mosney** [comment]
@ronggang 好 复现的时候我看一下

**Comment by Mosney** [comment]
`jquery-1.12.4.min.js:4 POST http://10.1.1.200:9091/transmission/rpc 409 (Conflict)
send @ jquery-1.12.4.min.js:4
ajax @ jquery-1.12.4.min.js:4
getSessionId @ transmission.min.js?v=20180417:2
init @ transmission.min.js?v=20180417:3
connect @ system.min.js?v=20180417:56
initdata @ system.min.js?v=20180417:13
(anonymous) @ system.min.js?v=20180417:8
(anonymous) @ system.min.js?v=20180417:7
i @ jquery-1.12.4.min.js:2
fireWith @ jquery-1.12.4.min.js:2
y @ jquery-1.12.4.min.js:4
c @ jquery-1.12.4.min.js:4
XMLHttpRequest.send (async)
send @ jquery-1.12.4.min.js:4
ajax @ jquery-1.12.4.min.js:4
n.(anonymous function) @ jquery-1.12.4.min.js:4
getScript @ jquery-1.12.4.min.js:4
(anonymous) @ system.min.js?v=20180417:6
i @ jquery-1.12.4.min.js:2
fireWith @ jquery-1.12.4.min.js:2
y @ jquery-1.12.4.min.js:4
c @ jquery-1.12.4.min.js:4
XMLHttpRequest.send (async)
send @ jquery-1.12.4.min.js:4
ajax @ jquery-1.12.4.min.js:4
n.(anonymous function) @ jquery-1.12.4.min.js:4
getScript @ jquery-1.12.4.min.js:4
setlang @ system.min.js?v=20180417:6
init @ system.min.js?v=20180417:8
(anonymous) @ system.min.js?v=20180417:109
i @ jquery-1.12.4.min.js:2
fireWith @ jquery-1.12.4.min.js:2
y @ jquery-1.12.4.min.js:4
c @ jquery-1.12.4.min.js:4
XMLHttpRequest.send (async)
send @ jquery-1.12.4.min.js:4
ajax @ jquery-1.12.4.min.js:4
n.(anonymous function) @ jquery-1.12.4.min.js:4
getScript @ jquery-1.12.4.min.js:4
(anonymous) @ system.min.js?v=20180417:109
i @ jquery-1.12.4.min.js:2
fireWith @ jquery-1.12.4.min.js:2
ready @ jquery-1.12.4.min.js:2
K @ jquery-1.12.4.min.js:2
`

**Comment by Mosney** [comment]
jquery-1.12.4.min.js:4 POST http://10.1.1.200:9091/transmission/rpc 409 (Conflict)
send @ jquery-1.12.4.min.js:4
ajax @ jquery-1.12.4.min.js:4
getSessionId @ transmission.min.js?v=20180417:2
init @ transmission.min.js?v=20180417:3
connect @ system.min.js?v=20180417:56
initdata @ system.min.js?v=20180417:13
(anonymous) @ system.min.js?v=20180417:8
(anonymous) @ system.min.js?v=20180417:7
i @ jquery-1.12.4.min.js:2
fireWith @ jquery-1.12.4.min.js:2
y @ jquery-1.12.4.min.js:4
c @ jquery-1.12.4.min.js:4
XMLHttpRequest.send (async)
send @ jquery-1.12.4.min.js:4
ajax @ jquery-1.12.4.min.js:4
n.(anonymous function) @ jquery-1.12.4.min.js:4
getScript @ jquery-1.12.4.min.js:4
(anonymous) @ system.min.js?v=20180417:6
i @ jquery-1.12.4.min.js:2
fireWith @ jquery-1.12.4.min.js:2
y @ jquery-1.12.4.min.js:4
c @ jquery-1.12.4.min.js:4
XMLHttpRequest.send (async)
send @ jquery-1.12.4.min.js:4
ajax @ jquery-1.12.4.min.js:4
n.(anonymous function) @ jquery-1.12.4.min.js:4
getScript @ jquery-1.12.4.min.js:4
setlang @ system.min.js?v=20180417:6
init @ system.min.js?v=20180417:8
(anonymous) @ system.min.js?v=20180417:109
i @ jquery-1.12.4.min.js:2
fireWith @ jquery-1.12.4.min.js:2
y @ jquery-1.12.4.min.js:4
c @ jquery-1.12.4.min.js:4
XMLHttpRequest.send (async)
send @ jquery-1.12.4.min.js:4
ajax @ jquery-1.12.4.min.js:4
n.(anonymous function) @ jquery-1.12.4.min.js:4
getScript @ jquery-1.12.4.min.js:4
(anonymous) @ system.min.js?v=20180417:109
i @ jquery-1.12.4.min.js:2
fireWith @ jquery-1.12.4.min.js:2
ready @ jquery-1.12.4.min.js:2
K @ jquery-1.12.4.min.js:2

**Comment by ronggang** [comment]
@Mosney 那是比较奇怪了，如果进度不走，要么就是数据没有刷新过来，只要提交出去的请求有得到正确的回复，进度就会刷新，除非返回了错误的数据，无法正确填充进度。
