### ISSUE TITLE
“当前种子属性”文件数目在特定情况下显示不正常

### ISSUE THREAD

**Issue by Mosney** [ronggang/transmission-web-control#237]
* Transmssion版本: 2.93
* Tr Web Control 版本: 1.6.0alpha
* 浏览器名称及版本：CentBrowser 3.2.4.23（正式版本） （64 位） (Chromium 64.0.3282.140)
* 问题描述:    
  

在不同PT站点辅种时发现的。有3个站点都有同一个资源，暂且命名为A、B、C，如下图所示

> 
![image](https://user-images.githubusercontent.com/22477230/39393363-07e64e2e-4af7-11e8-9c88-1b6fa6fdc58d.png)
其中A和C的种子内容和目录结构是一样的，如下图

> 
![image](https://user-images.githubusercontent.com/22477230/39393398-5a92a50a-4af7-11e8-85d4-6f3caf5c0fa8.png)
B种子在转载的时候去掉了封面和nfo信息，只剩下视频文件，暂且称之为单文件种B，如下图

> 
![image](https://user-images.githubusercontent.com/22477230/39393419-9b21446e-4af7-11e8-881e-34525b586d81.png)
 ### 问题来了 
在这三个种子之间来回切换时，”当前种子详情“下的”文件“一栏会出现问题，从只有一个文件的单文件种B切换到种A或者种B的时候，“文件”里会只显示只有一行，也就是说看起来只有一个文件，

> 
![image](https://user-images.githubusercontent.com/22477230/39393551-306c70a6-4af9-11e8-8391-c0e43f7b284f.png)
在“文件”里点击单独的刷新按钮能正确显示种A或者种C的三个文件。除此之外，从种A切换到种C,C-A,A-B,C-B,“文件”一栏显示都没有问题。
### 请开发者检查一下种子详情区域的刷新策略是否存在问题。

**Comment by ronggang** [comment]
@Mosney 是的，这是一个已知BUG，只要切换不同的种子时就会出现，还一直没有改 :sweat_smile:
