### ISSUE TITLE
執行 install-tr-control.sh 出現錯誤訊息

### ISSUE THREAD

**Issue by kuenming** [ronggang/transmission-web-control#238]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.93
* Tr Web Control 版本: V1.5.1
* 浏览器名称及版本：FireFox,Chrome
* 问题描述:
進行更新時,跳出 install-tr-control.sh: 113: install-tr-control.sh: Bad substitution [如圖](https://imgur.com/a/TGpt7SB)

**Comment by ronggang** [comment]
@kuenming 使用 bash 试试
sh 有几个命令不支持。
