### ISSUE TITLE
更新1.60Alpha版后，下载的预计时间处显示错误，详细见图

### ISSUE THREAD

**Issue by poppyseven** [ronggang/transmission-web-control#239]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 
<img width="318" alt="snipaste_2018-05-05_00-19-00" src="https://user-images.githubusercontent.com/38986756/39638796-eee62658-4ff9-11e8-8aea-b34b5ed1a449.png">

* Tr Web Control 版本: 
* 浏览器名称及版本：
Chrome
* 问题描述:

更新1.60Alpha版后，下载的预计时间处显示错误，详细见图
<img width="148" alt="snipaste_2018-05-05_00-14-25" src="https://user-images.githubusercontent.com/38986756/39638758-d18d89d4-4ff9-11e8-8814-dbf4343510c1.png">

**Comment by ronggang** [comment]
@poppyseven 请尝试清除缓存或恢复默认值试试。

**Comment by poppyseven** [comment]
现在好了，😁😁
