### ISSUE TITLE
typo: Saveing... instead of Saving...

### ISSUE THREAD

**Issue by sandrotosi** [ronggang/transmission-web-control#24]
Transmission Version:2.84 (14307), RPC: 15, WEB Control: 0.6 Beta(20130913) [as avail on qnap nas]

When saving the perferences the button shows a Saveing... label, while it should be Saving...

**Comment by sandrotosi** [comment]
with "WEB Control: 1.0 Beta(20141010)" it is so quick I cant tell what is the label after pressing Save, so it *might* be fixed

**Comment by sandrotosi** [comment]
nope, I verified and it is still there even in "WEB Control: 1.0 Beta(20141010)"

**Comment by DarkAlexWang** [comment]
#46
