### ISSUE TITLE
WEB GUI模式双TK地址问题

### ISSUE THREAD

**Issue by itmano** [ronggang/transmission-web-control#248]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.94
* Tr Web Control 版本: new
* 浏览器名称及版本：火狐
* 问题描述:当种子TK地址为2个或者更多的时候。如果有一个TK出错。有警告出现。这个问题只在WEB GUI出现。桌面版无问题。能否修复一下？
![qq 20180611144228](https://user-images.githubusercontent.com/40157136/41216209-f0db52ae-6d85-11e8-8d1c-28ff5983c8f3.png)

**Comment by ronggang** [comment]
@itmano 请使用最新的安装脚本，执行后，选择2，然后输入 53b7e07ad51116adef9aec5863ab581fc7638a08 ，等待下载完成后，看看问题有没有解决。
