### ISSUE TITLE
有计划支持 qBittorrent 吗

### ISSUE THREAD

**Issue by l-we** [ronggang/transmission-web-control#257]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 
* Tr Web Control 版本: 
* 浏览器名称及版本：
* 问题描述:

目前 qBittorrent webui 已经支持使用外部文件了，

**Comment by ronggang** [comment]
@l-we 抱歉，没有计划。
