### ISSUE TITLE
Add the option to hide some of the columns in download  section

### ISSUE THREAD

**Issue by sandrotosi** [ronggang/transmission-web-control#26]
Transmission Version:2.84 (14307), RPC: 15, WEB Control: 0.6 Beta(20130913) [as avail on qnap nas]

There might be some columns you are not particularly interested in (like the date the torrent was added) so having the option to select which columns to show would be appreciated

**Comment by ronggang** [comment]
Please update to the latest version.

**Comment by sandrotosi** [comment]
which is...?

**Comment by ronggang** [comment]
Latest version is 1.0 Beta(20141010). You used 0.6 Beta(20130913)

**Comment by sandrotosi** [comment]
This is indeed fixed in "WEB Control: 1.0 Beta(20141010)", closing.
