### ISSUE TITLE
制作和发布种子

### ISSUE THREAD

**Issue by i365star** [ronggang/transmission-web-control#260]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 
* Tr Web Control 版本: 
* 浏览器名称及版本：
* 问题描述:是否考虑增加制作和发布种子的功能呢？
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by ronggang** [comment]
以webui的名义做不了。
