### ISSUE TITLE
Manage language

### ISSUE THREAD

**Issue by vipera7** [ronggang/transmission-web-control#261]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 
* Tr Web Control 版本: 
* 浏览器名称及版本：
* 问题描述:
--------------------
## For English User 
Please provide the following information.
* Transmssion version:  
* Tr Web Control version:  1.6.0
* Browser name & version： Chrome
* Problem description:
Hello,

I would like to ask if it's possible to change language in the web ui ? Or force the language ?
Thank you

**Comment by DarkAlexWang** [comment]
Yes, you can change and select the language you want in the config panel (Base -> Language).
