### ISSUE TITLE
能否在校验种子的时候右击使用“获取更多peer(Ask tracker for more peers)”

### ISSUE THREAD

**Issue by Se7enMuting** [ronggang/transmission-web-control#263]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.94
* Tr Web Control 版本: v1.5.1-update-2
* 浏览器名称及版本：chrome 67
* 问题描述:
因为修改了文件，能跳过校验（在校验的时候右击 Ask tracker for more peers 可以跳过校验）。但是我发现大大的web控制器在校验的时候“获取更多peer”是灰色的.....大大可否告知下修改方法，让“获取更多peer”不变灰色？
感谢！！

**Comment by ronggang** [comment]
@Se7enMuting 这是设计时就做的限制，仅对活动中的种子有效，且仅能操作一个种子。
