### ISSUE TITLE
Sometimes columns are not sortable

### ISSUE THREAD

**Issue by sandrotosi** [ronggang/transmission-web-control#28]
Transmission Version:2.84 (14307), RPC: 15, WEB Control: 1.0 Beta(20141010)

it happens that sometimes a column is not sortable, but changing view (like from Active to Sending) and then click again on the  column to sort, will trigger the action

**Comment by simonbcn** [comment]
Same problem.
I want to order by ratio and I have to click on name and after on ratio.

**Comment by DarkAlexWang** [comment]
#46 Please check if the problem remains.
