### ISSUE TITLE
Firefox浏览器数据目录大小显示错位

### ISSUE THREAD

**Issue by magnww** [ronggang/transmission-web-control#281]
* Transmssion 版本: 2.94 
* Tr Web Control 版本: 1.6.0 beta(20180906)
* 浏览器名称及版本：Firefox 63
* 问题描述:
Firefox浏览器数据目录大小显示错位，如图
volumeUSB1大小应为6.19TB，向上错位了一行

![default](https://user-images.githubusercontent.com/7497333/48358488-d9b8f580-e6d5-11e8-9826-6d9e2649bd6e.png)

**Comment by GreatV** [comment]
same issue.
![](https://user-images.githubusercontent.com/17264618/55484786-b9291200-565b-11e9-8a83-cd0a6c7a177c.png)
