### ISSUE TITLE
功能建议：建议增加种子内容查看跟选择功能

### ISSUE THREAD

**Issue by DUHEI666** [ronggang/transmission-web-control#291]
现在导入种子后不能查看种子内带有的文件，不能选择性下载，这样我就得把所有文件下载下来，这样太麻烦了，希望能增加这个功能

**Comment by ronggang** [comment]
@DUHEI666 谢谢建议，以前有人提过了 
#107 #262

**Comment by DarkAlexWang** [comment]
Duplicated Question.
