### ISSUE TITLE
Save tags server-side

### ISSUE THREAD

**Issue by the-researcher** [ronggang/transmission-web-control#299]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 
* Tr Web Control 版本: 
* 浏览器名称及版本：
* 问题描述:
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 2.94 (d8e60ee44f)
* Tr Web Control version: 1.6.0 beta (20180906)
* Browser name & version：Google Chrome v.71.0.3578.98 (Official Build) (64-bit)
* Problem description:

1) I create and add tags to torrents on computer "A".

2) I close the browser window, and re-open Transmission WEB control on computer "A."
 Tags are saved.

3) I go to another browser on the same computer (i.e. FireFox on Computer "A"), and open Transmission WEB control. Tags are **not** present.

4) I go to another computer (computer "B"), and open Transmission WEB control. Tags are **not** present.

If the tagging information was saved server-side, it would allow users to access/organize content on other machines.

**Comment by ronggang** [comment]
@the-researcher 
This is temporarily not possible because the server does not have an interface available.

**Comment by DarkAlexWang** [comment]
Reopen if needed, but close for now.
