### ISSUE TITLE
在路由器上,安装tr-control-easy-install.sh,由于是https地址,wget无法验证证书导致安装失败

### ISSUE THREAD

**Issue by giveup** [ronggang/transmission-web-control#30]
应该加个--no-check-certificate的,不过我不会加....请求作者更新一下安装脚本,谢谢!

**Comment by zhanghaowx** [comment]
wget https://github.com/ronggang/transmission-web-control/raw/master/release/tr-control-easy-install.sh --no-check-certificate

**Comment by DarkAlexWang** [comment]
#47
