### ISSUE TITLE
Docker支持

### ISSUE THREAD

**Issue by zuosc** [ronggang/transmission-web-control#314]
update

-------------------------------------------------

https://hub.docker.com/r/linuxserver/transmission 已经内置该主题。

举例：
docker create \
  --name=transmission \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e TRANSMISSION_WEB_HOME=/transmission-web-control/ `#optional` \
  -p 9091:9091 \
  -p 51413:51413 \
  -p 51413:51413/udp \
  -v path to data:/config \
  -v path to downloads:/downloads \
  -v path to watch folder:/watch \
  --restart unless-stopped \
  linuxserver/transmission

**Comment by zuosc** [comment]
好的吧。暂时也解决了。

直接使用linuxserver/transmission  这个镜像就行。


然后把
/config
/watch
/downloads
映射出来就行了。

然后把`/usr/share/transmission/web`也映射出来，然后把web文件放在这里就行



顺便提一个小问题。使用这个镜像，如果直接使用你的脚本，会把/watch 识别为web目录

**Comment by Rhilip** [comment]
我觉得Docker镜像不应该由本项目提供。
这个repo的实质是transmission的一个第三方web界面，单独做Docker镜像没有意义。

**Comment by zuosc** [comment]
@Rhilip   你说的的确挺对的。  不过我觉得可以给他们提个PR   毕竟你这边属于他的一块。

只是建议~~

**Comment by ronggang** [comment]
> @Rhilip 你说的的确挺对的。 不过我觉得可以给他们提个PR 毕竟你这边属于他的一块。
> 
> 只是建议~~

谢谢建议，我觉得你可以把 docker 的安装方法做成教程，分享出来，这样以后大家可以照着做。:)

**Comment by LisonFan** [comment]
![image](https://user-images.githubusercontent.com/9424775/55391626-573daf00-556c-11e9-93af-c8efe6fa77a8.png)

突然发现已经内置了咱们项目了

**Comment by ronggang** [comment]
@LisonFan 这是什么项目？一个Docker？

**Comment by LisonFan** [comment]
> @LisonFan 这是什么项目？一个Docker？

https://hub.docker.com/r/linuxserver/transmission 就这个

**Comment by Rhilip** [comment]
> @LisonFan 这是什么项目？一个Docker？

Docker官方的transmission仓库，按照这个说明，只要修改里面指定的web_folder选项就可以用这个项目了

**Comment by ronggang** [comment]
那倒是挺方便的😄

**Comment by xiejiangtian** [comment]
> > @LisonFan 这是什么项目？一个Docker？
> 
> Docker官方的transmission仓库，按照这个说明，只要修改里面指定的web_folder选项就可以用这个项目了

请问这个web_folder在哪里呢
