### ISSUE TITLE
Sorting by ratio broken when there's an infinite in the list

### ISSUE THREAD

**Issue by jcdm** [ronggang/transmission-web-control#316]
Please provide the following information.
* Transmssion version: 2.95
* Tr Web Control version: 1.6.0 beta (20180906)
* Browser name & version：Chrome Version 72.0.3626.119

* Problem description:
When sorting by ratio complete, the interface sorts correctly on load, but then on the first (and subsequent) Auto Reloads the sort breaks into two lists both of which are correctly sorted, but with the 'infinite' ratio item (which is also listed as last activity 1970-01-01) between them. It seems one item is throwing off 'null' values and that's breaking the sort.

I don't see any pattern in what's sorted into each of the two lists. Added date, queue and number all seem to be unrelated.

On first load and sort, the 'nulls' are sorted to the end of the list (which I'd consider to be correct) but on the subsequent reloads they appear in the mix of the list, breaking the sorting of the other objects with them.

**Comment by jcdm** [comment]
![image](https://user-images.githubusercontent.com/2160585/53841726-6bce6c00-3fed-11e9-82fb-75528243a0b0.png)

**Comment by ronggang** [comment]
@jcdm Thanks for feedback.

**Comment by jcdm** [comment]
Gosh - that was fast! I was planning to have a crack at this myself in a few hours. Many thanks! I look forward to receiving it in the next update in due course 👍🏻

**Comment by ronggang** [comment]
@jcdm You can use the install script to update Webui to an unreleased version.  
![image](https://user-images.githubusercontent.com/8065899/53865637-9b4f9980-402a-11e9-991a-4e2f40a8e03a.png)

**Comment by jcdm** [comment]
That fix seems to have worked perfectly.

Thank you for that and the tip on installing! 🙏🏻

**Comment by ronggang** [comment]
You are welcome.
