### ISSUE TITLE
English insctuction for installation

### ISSUE THREAD

**Issue by goldriver2** [ronggang/transmission-web-control#317]
I am looking at the instruction to install the 1.6X or any version on a window system in English 

the link on the page links to an foreign language (?? chinese or japanese)

thanks for any help

**Comment by ronggang** [comment]
@goldriver2 Sorry, There is currently no English installation guide for the Windows version. Welcome to help.

**Comment by run-ze** [comment]
just replace files in transmission web directory with files under `src` directory

the transmission web directory maybe `C:\Program Files\Transmission\web`

better backup origin transmission web files before replace them
