### ISSUE TITLE
Torrent option doesn't work on mobile version

### ISSUE THREAD

**Issue by psycholyzern** [ronggang/transmission-web-control#320]
* Transmssion version: 2.94
* Tr Web Control version: Installed using "install-tr-control.sh", so I believe it is the latest (v1.6.0-beta2 )
* Browser name & version：Chrome Beta on Android (73.0.3683.75) and Firefox Nightly on Android (67.0a1)
* Problem description:

Hi. I access transmission webUI on my Android. 
But when I tap the "gear" icon next to the torrent's name, nothing happen.

![](https://i.imgur.com/qMIr5Tn.png)

**Comment by ronggang** [comment]
Sorry, is my problem, this feature has not been done yet. :sweat_smile:

**Comment by psycholyzern** [comment]
Oh. No problem.
Thanks for the reply :D
