### ISSUE TITLE
保存的下载目录是否可以删除

### ISSUE THREAD

**Issue by sagexy** [ronggang/transmission-web-control#337]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.94
* Tr Web Control 版本: 1.6.0 alpha
* 浏览器名称及版本：Chrome
* 问题描述: 添加种子的弹出框中 保存目录下载框里会保存所有的已下载的路径 由此一来如果路径一多起来就显得下拉列表太长了或者有些路径顶多使用一次却被永久保存起来了 所以我在想是否可以增加删除保存下载路径的功能 或者该数据保存在哪个文件里面 我手动去修改删除。望告知下下载目录的保存地址，谢谢大大！
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by ronggang** [comment]
@sagexy 目前是根据现有的种子自动分析后形成的目录列表，所以没有删除选项。
不过你说的问题，可以考虑加个排除列表什么。
