### ISSUE TITLE
gui希望能把端口等其他信息显示出来

### ISSUE THREAD

**Issue by 1265578519** [ronggang/transmission-web-control#339]
![1](https://user-images.githubusercontent.com/6442439/57160320-06470200-6e1b-11e9-89e7-2164d68bc9ca.png)
![QQ图片20190504031553](https://user-images.githubusercontent.com/6442439/57160321-06df9880-6e1b-11e9-94dd-e2009ef3659c.png)

gui希望能把端口等其他信息显示出来
看数据返回结果，上面是有port端口信息的，，希望加一下。
还有是否UTP连接，也有个单独的数据返回，也加一下吧，这样就知道是工作在UDP协议中了。。
![11](https://user-images.githubusercontent.com/6442439/57160348-1d85ef80-6e1b-11e9-9162-b7c1057a4a96.png)
还有这里点击刷新按钮tracker不会更新,,并且，
显示的是下载完成成功数量，而没有做种者和下载者数量显示，在数据中都有返回的，原生ui上面也有，希望搞下。

**Comment by imebeh** [comment]
那个更新按钮应该是分页组件的，点击任务列表的任务就可以更新tracker信息
