### ISSUE TITLE
希望能有对WEB 增加SSL的证书导入功能。

### ISSUE THREAD

**Issue by James-Jie** [ronggang/transmission-web-control#340]
希望能有对WEB 增加SSL的证书导入功能。
目前绝大多数的PT软件的WEB均支持在WEB界面导入SSL证书了TR的WEB还不支持

**Comment by Rhilip** [comment]
如果你指的是类似qb这样的功能，做不到。RPC没有这个接口哈。
![TIM截图20190504203845](https://user-images.githubusercontent.com/13842140/57179129-c2044200-6eac-11e9-86e5-140ee3dab507.png)
另外transmission的设置是针对session，一旦重启tr，通过网页设置的就会丢失。

**Comment by ronggang** [comment]
@James-Jie 抱歉，这个不在WebUI能力范围
