### ISSUE TITLE
关于梅林optware环境下的安装

### ISSUE THREAD

**Issue by yggp** [ronggang/transmission-web-control#342]
* Transmssion 版本: 2.82
* Tr Web Control 版本: 0.6 beta
* 浏览器名称及版本：Chrome 75
* 问题描述: Transmssion 是在路由器的梅林optware环境下用ipkg 装的 , 当时参照chh的帖子 , Web Control 是直接将文件覆盖到Transmssion 的web目录的 , 因为版本很久 , 想升级下Web Control , 但是现在的版本都是用shell脚本安装 ,需要为root 用户 , 然而梅林环境无法切换到root用户, 而且现在的src目录里的结构跟旧版差别很大 , 不敢直接复制到Transmssion的web目录,所以请问下 , 是否可以直接复制文件或者不需要root用户来执行shell

**Comment by ronggang** [comment]
@yggp 如果是手工更新，如果已经有 tr-web-control 目录，可按以下方法手工更新
- 把原来 `tr-web-control ` 目录删除
- 复制新的 `tr-web-control ` 目录到到 `web` 下
- 再把 `index.html` 和 `index.mobile.html` 文件覆盖即可

**Comment by yggp** [comment]
@ronggang 方法可行 , 已直接升级 , 非常感谢
