### ISSUE TITLE
gui上点右键，过一会右键菜单会自动消失

### ISSUE THREAD

**Issue by 1265578519** [ronggang/transmission-web-control#345]
2.94
webgui最新代码
谷歌最新浏览器
![2019-06-12_03-57-07](https://user-images.githubusercontent.com/6442439/59302348-5b055480-8cc6-11e9-8551-3f70fb9695a5.gif)

**Comment by ronggang** [comment]
@1265578519 是的，默认行为的确是这样子，不移到菜单上的话，一会儿就消失了。
下一版本可以考虑改为不自动消失。
