### ISSUE TITLE
安装后不生效

### ISSUE THREAD

**Issue by WeiKKJ** [ronggang/transmission-web-control#351]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.94 (d8e60ee44f)
* Tr Web Control 版本: 原版
* 浏览器名称及版本：chrome 75.0.3770.142
* 问题描述:我用的wd cloud ex2 ultra自带的Transmssion，按照教程一键安装找不到Transmssion安装目录，我手工指定目录后提示安装成功，但是web界面还是原版，没有发生任何变化。麻烦您看下怎么才能解决。
![image](https://user-images.githubusercontent.com/50602973/61957448-dd857180-aff1-11e9-9444-07c4f7f7ca6a.png)
![image](https://user-images.githubusercontent.com/50602973/61957473-e9713380-aff1-11e9-8909-e1395b13aecc.png)
![image](https://user-images.githubusercontent.com/50602973/61957495-f5f58c00-aff1-11e9-8b26-e384c123486a.png)
![image](https://user-images.githubusercontent.com/50602973/61957532-132a5a80-aff2-11e9-867b-3ed5f9a380d1.png)

--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by ronggang** [comment]
@WeiKKJ 如果路径正确，强制刷新应该就有了。

**Comment by WeiKKJ** [comment]
怎么看着ex2 ultra这个版本的Tr和其他版本的安装位置不一样呢，您看下这几个目录
![image](https://user-images.githubusercontent.com/50602973/61963194-a74def00-affd-11e9-892a-eb55e92d08e5.png)
![image](https://user-images.githubusercontent.com/50602973/61963196-a7e68580-affd-11e9-84a3-069aa9db34b4.png)
![image](https://user-images.githubusercontent.com/50602973/61963218-b03ec080-affd-11e9-954d-fa3b9bb1324a.png)
![image](https://user-images.githubusercontent.com/50602973/61963239-baf95580-affd-11e9-93ac-a000c2c62010.png)

**Comment by WeiKKJ** [comment]
解决了，我用debian重新安装了一个Tr，然后更换UI，把生效的文件替换到ex2 ultra的/mnt/HD/HD_a2/Nas_Prog/Transmission/web_transmission目录就好了。
![image](https://user-images.githubusercontent.com/50602973/61963803-0a8c5100-afff-11e9-9f6f-6f80b7390d4b.png)
![image](https://user-images.githubusercontent.com/50602973/61963831-1bd55d80-afff-11e9-8269-82bc87818699.png)
