### ISSUE TITLE
关于使用nginx反向代理transmission web ui 后无法添加大种子文件的情况

### ISSUE THREAD

**Issue by pdxgf1208** [ronggang/transmission-web-control#352]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.92
* Tr Web Control 版本: 1.6.0
* 浏览器名称及版本：Firefox与Chrome 最新版
* 问题描述: 经过nginx反向代理后，Web UI的其他功能均没有异常，但在添加种子文件时，文件分片较多的种子文件会添加失败（一直卡在添加页面），使用原始端口没有这个问题。请教下如何配置nginx反向代理可以解决这个问题。
目前的nginx代理配置：
 location /transmission {

        location /transmission/rpc {
                proxy_pass http://127.0.0.1:10002;
        }

        location /transmission/web/ {
                proxy_pass http://127.0.0.1:10002;
        }

        location /transmission/upload {
                proxy_pass http://127.0.0.1:10002;
        }

        location /transmission/web/style/ {
                alias /usr/share/transmission/web/style/;
        }

        location /transmission/web/javascript/ {
                alias /usr/share/transmission/web/javascript/;
        }

        location /transmission/web/images/ {
                alias /usr/share/transmission/web/images/;
        }

        location /transmission/ {
                return 301 https://$server_name/transmission/web;
        }
        }

**Comment by zhuwenbing** [comment]
以下配置也许对你有所帮助
http {
    ......
    client_max_body_size 15m;
    ......
}

**Comment by pdxgf1208** [comment]
> 
> 
> 以下配置也许对你有所帮助
> http {
> ......
> client_max_body_size 15m;
> ......
> }
> Syntax: client_max_body_size size; Default: client_max_body_size 1m; Context: http, server, location

非常感谢，已经实验成功。
