### ISSUE TITLE
请问如何添加HTTPS支持。

### ISSUE THREAD

**Issue by mqdlzh** [ronggang/transmission-web-control#356]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.94 (d8e60ee44f), RPC: 15
* Tr Web Control 版本: 1.6.0 beta (20180906)
* 浏览器名称及版本：Google Chrome 版本 74.0.3729.169（正式版本） （64 位）
* 问题描述: 因需要外网访问，群晖里开启了DDNS和HSTS,默认打开界面就是HTTPS，像问一问是否有办法添加HTTPS链接支持。
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 2.94 (d8e60ee44f), RPC: 15
* Tr Web Control version: 1.6.0 beta (20180906)
* Browser name & version：Google Chrome Version 74.0.3729.169 （64 Bit）
* Problem description: How to add HTTPS support for Tr Web Control.

**Comment by Rhilip** [comment]
Transmission 本身不直接支持SSL，请考虑在web面板前套一层支持SSL的web服务器（如Nginx Caddy）。
此问题不在本repo的支持范围内，请去Transmission社区咨询。

**Comment by mqdlzh** [comment]
> Transmission 本身不直接支持SSL，请考虑在web面板前套一层支持SSL的web服务器（如Nginx Caddy）。
> 此问题不在本repo的支持范围内，请去Transmission社区咨询。

那个，不是很懂如何在群晖里配置Nginx Caddy，有什么帖子指引吗？麻烦了。

**Comment by mqdlzh** [comment]
> Transmission 本身不直接支持SSL，请考虑在web面板前套一层支持SSL的web服务器（如Nginx Caddy）。
> 此问题不在本repo的支持范围内，请去Transmission社区咨询。

打扰了，我自己解决了，使用的是群晖的反向代理服务设置就好了。。。
![Snipaste_2019-09-01_20-45-30](https://user-images.githubusercontent.com/31967654/64076604-84e47b00-ccf9-11e9-8291-1ef478a82fcd.jpg)
![Snipaste_2019-09-01_20-50-35](https://user-images.githubusercontent.com/31967654/64076666-3388bb80-ccfa-11e9-9941-a69664ec97fd.jpg)
