### ISSUE TITLE
使用最新版Firefox浏览器出现标签错位问题

### ISSUE THREAD

**Issue by pdxgf1208** [ronggang/transmission-web-control#357]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.92
* Tr Web Control 版本: 1.6.0 beta
* 浏览器名称及版本：Firefox 69.0
* 问题描述:如下图，服务器分布与数据分布发生标签错位
![image](https://user-images.githubusercontent.com/33011786/64537482-79263380-d34d-11e9-9f1d-ea06dd67c777.png)
使用Firefox浏览器，禁用所有拓展后的截图

使用Chrome浏览器标签正常

**Comment by ronggang** [comment]
@pdxgf1208 此Bug已修复，用脚本更新至当前仓库最新代码即可。
