### ISSUE TITLE
[Request]希望能增加单种限速的功能

### ISSUE THREAD

**Issue by ted423** [ronggang/transmission-web-control#360]
下了GUI是可以设置的
主要有时候发种需要保障下发种带宽

**Comment by ronggang** [comment]
单种限速在种子属性里可以设置。

**Comment by ted423** [comment]
> 单种限速在种子属性里可以设置。

![image](https://user-images.githubusercontent.com/7042766/66574980-c47b6e00-eba7-11e9-9b97-a038db9e607a.png)
我看这里写的global？并且设置后刷新再点击看起来没启用？

**Comment by ted423** [comment]
我又试了一下，GUI上设置的确实会在这里打上勾
GUI的那里没加Global，可能写错了？

~~但是这里设置点save就会报错~~

~~Failed to load resource: the server responded with a status of 409 (Conflict)~~

又确认了下，是英文有问题，中文是正常的，没有全局

设置的时候要把自动刷新关掉，不然刷新就会影响设置

**Comment by ted423** [comment]
又试了一下，貌似不能批量设，一次只设成功了一个
