### ISSUE TITLE
所有的种子都会显示警告

### ISSUE THREAD

**Issue by Cye3s** [ronggang/transmission-web-control#37]
不管是PT还是普通的PT种子，又看不到警告信息是什么，都能正常下载和做种

![screen](https://cloud.githubusercontent.com/assets/2126873/10961892/2c67ae8e-83ce-11e5-8d7f-715d16a258d9.png)

Transmission 版本：2.84 (14307), RPC: 15, WEB Control: 1.0 Beta(20141010)
系统 Ubuntu 14.04.3 LTS x64

**Comment by dingchong** [comment]
这是由于种子信息里面包含有失效的tracker服务器导致的，并不会影响到正常的使用。

**Comment by Cye3s** [comment]
应该没失效的tracker哇，是PT种，tracker就这么一个，失效了还能下？
![qq 20151109161503](https://cloud.githubusercontent.com/assets/2126873/11029048/0b9d135e-86ff-11e5-86ae-5f29698afac9.png)

**Comment by dingchong** [comment]
那看来与我遇到的是不同问题，我下载的是普通的bt种子，失效的tracker是会提示警告。

**Comment by Cye3s** [comment]
我找到原因了，不知道为什么，我的Transmission 2.84的RPC接口返回的JSON，里面的结果有中文，而js里判断状态是用英文，造成一直是失败状态，虽然代码里改成中文应该能行，但这个通用性太差
![qq 20151119110359](https://cloud.githubusercontent.com/assets/2126873/11261259/b7030fc2-8ead-11e5-9267-f61598a1ef70.png)
![qq 20151119110501](https://cloud.githubusercontent.com/assets/2126873/11261264/bd96f182-8ead-11e5-89f5-f3ad0664c583.png)

**Comment by DarkAlexWang** [comment]
No more new conversation, please reopen it if you think it is necessary.

**Comment by Cye3s** [comment]
@DarkAlexWang 目前是Ubuntu 14.04.5 LST上ppa安装的2.9.2还是有这问题
sudo add-apt-repository ppa:transmissionbt/ppa
每次更新去改js代码也不现实，我怀疑是ubuntu上的transmission中文语言的问题，把不该翻译的一个sussess翻译了

能帮忙看下原因么

**Comment by ronggang** [comment]
@Cye3s 感谢反馈，确实是BUG，下次更新时修复。

**Comment by Cye3s** [comment]
看到新commit，pull了最新代码来测试，问题已经解决了，可以close了
