### ISSUE TITLE
更新Wiki：DSM 一键安装以及英文描述

### ISSUE THREAD

**Issue by XIAZY** [ronggang/transmission-web-control#374]
Github 不能给 wiki 提 pull request，我就写在这里了，见谅

这是更新的内容：
https://github.com/XIAZY/TransmissionWebControl-Wiki/commit/5e6fe6a54bcaccaaef3ede14fdd57eff02b8be44

主要增加了一件安装脚本和英文描述，DSM用户不再需要上传脚本、设权限什么的了。以后如果安装脚本更新了也没有任何问题

**Comment by ronggang** [comment]
@XIAZY 
- 可否把图片换成 `images` 目录下，那个外链正常情况下打不开；
- 用于记录日志的目录要说明一下，就是那个 `/volume1/MyFolder/install-tr-control-cn-log.txt` 路径；
- 第四点应该变成第二了；

**Comment by XIAZY** [comment]
修好了，👌
https://github.com/XIAZY/TransmissionWebControl-Wiki

**Comment by ronggang** [comment]
已合并。

**Comment by XIAZY** [comment]
感谢你的项目
