### ISSUE TITLE
有没有什么办法可以将自动刷新时间修改为1秒或者1秒以下达到实时刷新的效果

### ISSUE THREAD

**Issue by Zayia** [ronggang/transmission-web-control#377]
* Transmssion 版本: 2.9.4
* Tr Web Control 版本: 1.6.0 (20190724)
* 浏览器名称及版本：chrome
* 问题描述:有没有什么办法可以将自动刷新时间修改为1秒或者1秒以下达到实时刷新的效果

**Comment by ronggang** [comment]
默认最小3秒钟轮询，如果要调，可自己调代码，调整“min” 值
https://github.com/ronggang/transmission-web-control/blob/91ea7ab968d5f1e044b2ee3e062c54384de43cd3/src/tr-web-control/script/system.js#L1241-L1252

**Comment by Zayia** [comment]
测试无效呀

**Comment by ronggang** [comment]
> 测试无效呀

实际线上环境要调整 `script/min/system.min.js` 文件。

**Comment by Zayia** [comment]
问题解决了

**Comment by 1265578519** [comment]
修改方法，控制台F12输入
```
刷新毫秒=1000;if(system.config.autoReload){document.getElementById('toolbar_autoreload').click();}setInterval(function(){document.getElementById('toolbar_reload').click();},刷新毫秒);document.getElementById('toolbar_autoreload').remove();
```
可以加成书签，点击书签直接生效

**Comment by Zayia** [comment]
补充一下，system.min.js文件位于
`/volumeX/@appstore/transmission/share/transmission/web/tr-web-control/script/min目录下`
楼上说的将代码加入书签也行，但是需要在前面加上
`javascript:刷新毫秒=1000;if(system.config.autoReload){document.getElementById('toolbar_autoreload').click();}setInterval(function(){document.getElementById('toolbar_reload').click();},刷新毫秒);document.getElementById('toolbar_autoreload').remove();`
