### ISSUE TITLE
拒绝连接，这是什么原因？

### ISSUE THREAD

**Issue by hzpinbo** [ronggang/transmission-web-control#380]
* Transmssion 版本: 2.94-16
* Tr Web Control 版本: 1.5.1
* 浏览器名称及版本：360极速浏览器 12.0.1053.0
* 问题描述:
安装系统：群晖 DS6.1.7-15384 P3
终端软件：putty
参考安装方法：https://github.com/ronggang/transmission-web-control/wiki/Installation-For-DSM-CN
参照您提供的安装方法的前两种方式安装均不成功，"通过Windows图形界面安装"这种方法因图片链接失效有些地方不明白没有测试，具体“通过SSH安装”出现以下问题(操作前已获得root权限)，下面列出wget 路径后出现的提示。
root@MYNAS:~# wget  https://github.com/ronggang/transmission-web-control/raw/master/release/install-tr-control-cn.sh
--2020-02-25 10:37:05--  https://github.com/ronggang/transmission-web-control/raw/master/release/install-tr-control-cn.sh
Resolving github.com... 13.229.188.59
Connecting to github.com|13.229.188.59|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/ronggang/transmission-web-control/master/release/install-tr-control-cn.sh [following]
--2020-02-25 10:37:05--  https://raw.githubusercontent.com/ronggang/transmission-web-control/master/release/install-tr-control-cn.sh
Resolving raw.githubusercontent.com... 151.101.228.133
Connecting to raw.githubusercontent.com|151.101.228.133|:443... failed: Connection refused.
root@MYNAS:~# 

--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by ronggang** [comment]
请手动检查连接github是否通畅。
