### ISSUE TITLE
请考虑加入多个时段上传下载控制

### ISSUE THREAD

**Issue by fyngd** [ronggang/transmission-web-control#383]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.94
* Tr Web Control 版本: 1.6.0 (20190724)
* 浏览器名称及版本：chrome 80.0.3987.122
* 问题描述：目前的版本只能设置一个时段，希望能加入多个时段控制。这样能充分利用上班时间挂PT，下班时间限速不影响emby类的媒体服务器向外提供服务。
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by ronggang** [comment]
这个非webui可控制，请考虑其他方式来实现。
