### ISSUE TITLE
RSS Feed not working

### ISSUE THREAD

**Issue by JazzyStahh** [ronggang/transmission-web-control#395]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 
* Tr Web Control 版本: 
* 浏览器名称及版本：
* 问题描述:
--------------------
## For English User 
Please provide the following information.
* Transmssion version: Transmission: 2.94 (d8e60ee44f), RPC: 15
* Tr Web Control version: Web Control: 1.6.0 beta (20180906)
* Browser name & version：Chrome Version 80.0.3987.163 (Official Build) (64-bit)
* Problem description:

I have tried multiple times to add RSS Feeds into the tnas/terra-master hosted transmission.

This is the link: https://zooqle.com/rss/tv/1thm6jjycm.rss

But it never seems to work. 

I have also used showrss.info rss links but they do not work either.

How can I fix this?

**Comment by ronggang** [comment]
This feature is not supported.
