### ISSUE TITLE
移动版种子栏最右边设置图标无反应

### ISSUE THREAD

**Issue by lihoru99** [ronggang/transmission-web-control#4]
移动版的种子栏最右边的设置图标有什么功能呢，在手机和电脑上测试过，点击这个按钮没有任何反应。
对于小屏手机，这一溜标签占据了较大版面，而且不能隐藏，望优化。
PS：现在的移动版选择框就比较好，往左搓就会隐藏掉。
![default](https://cloud.githubusercontent.com/assets/9137115/4609392/8bd4761c-529d-11e4-9cf7-0e4a5a75f70e.png)

**Comment by DarkAlexWang** [comment]
No more new conversation.
