### ISSUE TITLE
"Folders Dictionary" explanation?

### ISSUE THREAD

**Issue by simonbcn** [ronggang/transmission-web-control#40]
What is the syntax of "Folders Dictionary" tab?

**Comment by jeroenpeters1986** [comment]
Currently, I just get an 'undefined' here

**Comment by DarkAlexWang** [comment]
#46

**Comment by LandonSRoberts** [comment]
Any update on this?

**Comment by OscarVanL** [comment]
What is this section for?

**Comment by ronggang** [comment]
> What is this section for?

You can specify some preset values, one line per directory, these directories can be used for target path selection when adding torrents, or used for `Automatically matches data directory`, like this:
https://github.com/ronggang/transmission-web-control/issues/220#issuecomment-382931740
