### ISSUE TITLE
Delete torrent with data?

### ISSUE THREAD

**Issue by simonbcn** [ronggang/transmission-web-control#41]
Is there any option to delete torrent and data?

**Comment by ioxenus** [comment]
Of course, just click "Remove" (you can find it in the context menu if you right-click it on the torrent; or select the torrent and choose the red X in the toolbar) and check the "Delete local data" box:
![image](https://cloud.githubusercontent.com/assets/1121580/15451633/798ca418-1fd6-11e6-9b3b-d305a1edb8c8.png)
