### ISSUE TITLE
Different UIs show different values?

### ISSUE THREAD

**Issue by AbrahamGlasser** [ronggang/transmission-web-control#412]
Originally posted here: https://github.com/haugene/docker-transmission-openvpn/issues/1160

Hi,

I switched between the [original ](https://github.com/haugene/docker-transmission-openvpn) and the "web control" UIs, and I think there is a discrepancy between the various values shown for torrents. The different UIs show different values.

[Here is a screenshot of the different UIs showing different values between them.](https://imgur.com/a/M8wF2Uk)

Particularly the **file sizes and peer statistics seem different and misleading**. For example, I saw 2000+ peers were connected in the web-control UI, while the original UI showed 24 peers connected. The downloading percentage between the different UIs seem fine, as does the download/upload speed.

I wasn't sure if this was a bug, hope it's helpful! Let me know if you need any more information! I am running this via Docker on a Synology NAS (DS218+).

**Comment by imebeh** [comment]
https://github.com/transmission/transmission/blob/master/web/javascript/formatter.js

The original transmission webui use 1000 not 2^10 to calculate size and speed

**Comment by AbrahamGlasser** [comment]
That might explain the file sizes!

However, that doesn't seem to explain the difference in the **number of peers**. Do you know about that?

**Comment by imebeh** [comment]
![image](https://user-images.githubusercontent.com/1243962/80931492-bc597900-8dec-11ea-9e69-4efdc594b7cb.png)

**Comment by AbrahamGlasser** [comment]
Ah, that makes sense!

Thank you very much :)
