### ISSUE TITLE
error when install

### ISSUE THREAD

**Issue by unrarc** [ronggang/transmission-web-control#413]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本:        2.94-16
* Tr Web Control 版本:    1.6.0 beta
* 浏览器名称及版本：    chrome 81.0.4044.129
* 问题描述:                      下载目录改为大写后，之前下载的文件报错，无法解决，所以卸载重装，用putty以ssh建立连接并下载时报错，改为--no-check-certificate后下载完毕，执行bash install-tr-control.sh，报错：
install-tr-control.sh: line 1: syntax error near unexpected token `newline'
install-tr-control.sh: line 1: `<!DOCTYPE html>'

**Comment by RtYkk** [comment]
重装，多半也是GitHub被墙的锅。
你这是把一个网页下载下来了
把涉及到GitHub的部分用Gitee替代掉试试看，比如利用下面这个现成的Fork

[https://gitee.com/cz7777/transmission-web-control](https://gitee.com/cz7777/transmission-web-control)

**Comment by unrarc** [comment]
> 重装，多半也是GitHub被墙的锅。
> 你这是把一个网页下载下来了
> 把涉及到GitHub的部分用Gitee替代掉试试看，比如利用下面这个现成的Fork
> 
> https://gitee.com/cz7777/transmission-web-control

谢谢指点，知道原因就好办了。手动下载sh，然后尝试winscp上传，没root权限，折腾半天无果，vim复制文本内容粘贴进去，然后bash，大功告成，再次感谢，fu*k CCP!

**Comment by RtYkk** [comment]
如果解决了，建议close掉issue。没办法，国内就这网络环境，raw.githubusercontent.com应该是完全挂了

**Comment by DarkAlexWang** [comment]
Thank you all for the help.
