### ISSUE TITLE
强烈建议将本repo fork一份去Gitee

### ISSUE THREAD

**Issue by RtYkk** [ronggang/transmission-web-control#414]
GitHub墙越来越高，各种安装失败大抵都是因为被墙访问错误导致的，解决这个问题其实很简单，就是国内做个镜像源，最简单的就是Gitee。现在Gitee上已经有三四个左右公开的本repo的fork，但是还是希望您能亲自fork一份过去并在GitHub中加一段国内的安装方法来解决访问问题。

**Comment by ronggang** [comment]
之前想去gitee注册一个账号进行仓库镜像，但发现同名被人注册了，而且好像这个账号不活动，不知道能不能要过来。

**Comment by tea1111980** [comment]
希望能找到 同名注册的那个用户，跟他说一下。

**Comment by ronggang** [comment]
> 希望能找到 同名注册的那个用户，跟他说一下。

尝试联系过，暂时没有回复。
我已创建一个镜像：
https://gitee.com/culturist/transmission-web-control

**Comment by RtYkk** [comment]
感觉联系上还是挺难的……唯一知道的就是一个gitee账号，还是一个长期不用的废弃账号。一个repo也没有……
镜像过去好像也只是暂时解决了shell脚本下载不下来的问题，看了看脚本里面可能还有一些和GitHub产生交互的地方需要替换
