### ISSUE TITLE
在Ubuntu20中无法替换原有UI

### ISSUE THREAD

**Issue by windyOC** [ronggang/transmission-web-control#415]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.94
* Tr Web Control 版本: 
* 浏览器名称及版本：chrome 、edge、firefox，皆为最新版且关闭缓存
* 问题描述:运行脚本后，UI依然为原版UI，手动删除/usr/share下的web文件后，tr也依然可以200响应，显然文件目录已发生变更，但是全盘扫描后并不能找到相关文件目录。
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by ronggang** [comment]
可能需要手工查找一下TR的WEB目录，然后指定这个目录再进行安装。

**Comment by windyOC** [comment]
实际上我已经手工查找过了，用find进行了全盘扫描js和css文件

**Comment by ronggang** [comment]
那这个已超出我的能力范围。😅

**Comment by windyOC** [comment]
大哥快去啃transmission的源码（狗头），我相信你可以的

**Comment by imebeh** [comment]
可以用环境变量 `TRANSMISSION_WEB_HOME ` 指定webui 的位置


https://github.com/transmission/transmission/wiki/Environment-Variables

**Comment by windyOC** [comment]
> 可以用环境变量 `TRANSMISSION_WEB_HOME` 指定webui 的位置
> 
> https://github.com/transmission/transmission/wiki/Environment-Variables

实际上我已经尝试过了，但是似乎没有效果

**Comment by imebeh** [comment]
> 实际上我已经尝试过了，但是似乎没有效果

我的是用在systemd启动文件中设置的，有效果

**Comment by madAndroid** [comment]
Thanks, I managed to fix this with the following systemd unit file:
```
# cat /lib/systemd/system/transmission-daemon.service
[Unit]
Description=Transmission BitTorrent Daemon
After=network.target

[Service]
User=debian-transmission
Type=notify
Environment="TRANSMISSION_WEB_HOME=/usr/share/transmission/web/"
ExecStart=/usr/bin/transmission-daemon -f --log-error
ExecStop=/bin/kill -s STOP $MAINPID
ExecReload=/bin/kill -s HUP $MAINPID

[Install]
WantedBy=multi-user.target
```

**Comment by derrick-null** [comment]
Same issue here. After run the install script for serval times. I found that transmission-web-control codes are install in this path:
`
/usr/share/transmission/web/transmission-web-control-master/src
`
So you have to set the TRANSMISSION_WEB_HOME=/usr/share/transmission/web/transmission-web-control-master/src.
NOT /usr/share/transmission/web/
