### ISSUE TITLE
关于删除添加种子页面下保存目录下拉框的历史目录

### ISSUE THREAD

**Issue by jttqbc** [ronggang/transmission-web-control#416]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.94 
* Tr Web Control 版本: 1.6.0 beta (20180906)
* 浏览器名称及版本：Firefox、Chrome
* 问题描述:点击添加种子后，页面的“保存目录”下拉框中有很多历史目录的记录，很多已经用不到了，请问如何删除。
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by imebeh** [comment]
删了那个目录的下载任务

**Comment by jttqbc** [comment]
> 
> 
> 删了那个目录的下载任务

没有其他办法了吗，毕竟正在挂pt，做种中，直接删除的话就不能做种了。

**Comment by imebeh** [comment]
> 没有其他办法了吗，毕竟正在挂pt，做种中，直接删除的话就不能做种了。

webui里面设置移动到其他目录（移动数据），没有任务的目录就不会再出现在历史列表中
