### ISSUE TITLE
Transmission 3.00 发布了

### ISSUE THREAD

**Issue by LsnmxNB** [ronggang/transmission-web-control#425]
Allow the RPC server to listen on an IPv6 address (#161)
Change TR_CURL_SSL_VERIFY to TR_CURL_SSL_NO_VERIFY and enable verification by default (#334)
Go back to using hash as base name for resume and torrent files (those stored in configuration directory) (#122)
Handle "fields" argument in "session-get" RPC request; if "fields" array is present in arguments, only return session fields specified; otherwise return all the fields as before
Limit the number of incorrect authentication attempts in embedded web server to 100 to prevent brute-force attacks (#371)
Set idle seed limit range to 1..40320 (4 weeks tops) in all clients (#212)
Add Peer ID for Xfplay, PicoTorrent, Free Download Manager, Folx, Baidu Netdisk torrent clients (#256, #285, #355, #363, #386)
Announce INT64_MAX as size left if the value is unknown (helps with e.g. Amazon S3 trackers) (#250)
Add TCP_FASTOPEN support (should result in slight speedup) (#184)
Improve ToS handling on IPv6 connections (#128, #341, #360, #692, #737)
Abort handshake if establishing DH shared secret fails (leads to crash) (#27)
Don't switch trackers while announcing (leads to crash) (#297)
Improve completion scripts execution and error handling; add support for .cmd and .bat files on Windows (#405)
Maintain a "session ID" file (in temporary directory) to better detect whether session is local or remote; return the ID as part of "session-get" response (TRAC-5348, #861)
Change torrent location even if no data move is needed (#35)
Support CIDR-notated blocklists (#230, #741)
Update the resume file before running scripts (#825)
Make multiscrape limits adaptive (#837)
Add labels support to libtransmission and transmission-remote (#822)
Parse session-id header case-insensitively (#765)
Sanitize suspicious path components instead of rejecting them (#62, #294)
Load CA certs from system store on Windows / OpenSSL (#446)
Add support for mbedtls (formely polarssl) and wolfssl (formely cyassl), LibreSSL (#115, #116, #284, #486, #524, #570)
Fix building against OpenSSL 1.1.0+ (#24)
Fix quota support for uClibc-ng 1.0.18+ and DragonFly BSD (#42, #58, #312)
Fix a number of memory leaks (magnet loading, session shutdown, bencoded data parsing) (#56)
Bump miniupnpc version to 2.0.20170509 (#347)
CMake-related improvements (Ninja generator, libappindicator, systemd, Solaris and macOS) (#72, #96, #117, #118, #133, #191)
Switch to submodules to manage (most of) third-party dependencies
Fail installation on Windows if UCRT is not installed
Mac Client
Bump minimum macOS version to 10.10
Dark Mode support (#644, #722, #757, #779, #788)
Remove Growl support, notification center is always used (#387)
Fix autoupdate on High Sierra and up by bumping the Sparkle version (#121, #600)
Transition to ARC (#336)
Use proper UTF-8 encoding (with macOS-specific normalization) when setting download/incomplete directory and completion script paths (#11)
Fix uncaught exception when dragging multiple items between groups (#51)
Add flat variants of status icons for message log (#134)
Optimize image resources size (#304, #429)
Update file icon when file name changes (#37)
Update translations
GTK+ Client
Add queue up/down hotkeys (#158)
Modernize the .desktop file (#162)
Add AppData file (#224)
Add symbolic icon variant for the Gnome top bar and when the high contrast theme is in use (#414, #449)
Update file icon when its name changes (#37)
Switch from intltool to gettext for translations (#584, #647)
Update translations, add new translations for Portuguese (Portugal)
Qt Client
Bump minimum Qt version to 5.2
Fix dropping .torrent files into main window on Windows (#269)
Fix prepending of drive letter to various user-selected paths on Windows (#236, #307, #404, #437, #699, #723, #877)
Fix sorting by progress in presence of magnet transfers (#234)
Fix .torrent file trashing upon addition (#262)
Add queue up/down hotkeys (#158)
Reduce torrent properties (file tree) memory usage
Display tooltips in torrent properties (file tree) in case the names don't fit (#411)
Improve UI look on hi-dpi displays (YMMV)
Use session ID (if available) to check if session is local or not (#861)
Use default (instead of system) locale to be more flexible (#130)
Modernize the .desktop file (#162)
Update translations, add new translations for Afrikaans, Catalan, Danish, Greek, Norwegian Bokmål, Slovenian
Daemon
Use libsystemd instead of libsystemd-daemon (TRAC-5921)
Harden transmission-daemon.service by disallowing privileges elevation (#795)
Fix exit code to be zero when dumping settings (#487)
Web Client
Fix tracker error XSS in inspector (CVE-?)
Fix performance issues due to improper use of setInterval() for UI refresh (TRAC-6031)
Fix recognition of https:// links in comments field (#41, #180)
Fix torrent list style in Google Chrome 59+ (#384)
Show ETA in compact view on non-mobile devices (#146)
Show upload file button on mobile devices (#320, #431, #956)
Add keyboard hotkeys for web interface (#351)
Disable autocompletion in torrent U

**Comment by tea1111980** [comment]
卧槽！它，终于 还是来了~~

**Comment by BigPig0** [comment]
是不是升级后恢复成默认ui了

**Comment by xiaoyaoyuxin** [comment]
本项目能及时跟进么?希望这么好的UI，不要放弃啊。

**Comment by LsnmxNB** [comment]
@ronggang
大佬更新一下，麻烦了

**Comment by ronggang** [comment]
有人试过在3.0上使用吗？是否会有问题？

**Comment by LsnmxNB** [comment]
> 有人试过在3.0上使用吗？是否会有问题？

我再等等就更新，3.0刚发布，变态PT网站还没支持Transmission 3.0，大佬麻烦了

**Comment by DarkAlexWang** [comment]
我今天试了下，在Mac上的brew装的transmission 3.0，web interface 正常使用，没啥问题，就是好多PT站貌似还不支持3.0，都是提示客户端不支持。

**Comment by imebeh** [comment]
https://github.com/transmission/transmission/blob/7e1da2d8fe5c95299414e013aee6cbae3b1e2e65/extras/rpc-spec.txt#L806
新增几条可获取的状态，都是向后兼容的

**Comment by DarkAlexWang** [comment]
我CHDBits 不支持，有空试下别的站。。。

**Comment by LsnmxNB** [comment]
@DarkAlexWang  CHDBits 这垃圾我不玩了，胡乱封号，当年好不容易养了100T上行，结果关站，重开后说数据没了，又重新注册胡乱封号说多都是泪

**Comment by LsnmxNB** [comment]
@ronggang  [root@ns361178 transmission-3.00]# transmission-daemon -V
transmission-daemon 3.00 (bb6b5a062e)
transmission-web-control识别的还是2.94

<img width="1122" alt="Snipaste_2020-06-28_15-23-51" src="https://user-images.githubusercontent.com/42826027/85941146-a337f900-b953-11ea-991b-9ae6ff15bfec.png">

**Comment by imebeh** [comment]
> @ronggang  [root@ns361178 transmission-3.00]# transmission-daemon -V
> 
> transmission-daemon 3.00 (bb6b5a062e)
> 
> transmission-web-control识别的还是2.94
> 
> 
> 
可以考虑用仓库的版本，用的时候顺便改一下index.html用非min版的system.js、transmissin*.js

**Comment by LsnmxNB** [comment]
> > @ronggang  [root@ns361178 transmission-3.00]# transmission-daemon -V
> > transmission-daemon 3.00 (bb6b5a062e)
> > transmission-web-control识别的还是2.94
> 
> 可以考虑用仓库的版本，用的时候顺便改一下index.html用非min版的system.js、transmissin*.js

谢谢，动手能力有限啊，小学文化，便改一下index.html用非min版的system.js、transmissin*.js就太复杂了

**Comment by Joey0217** [comment]
群晖升级3.0后web control失效了，小白也不敢瞎折腾，坐等大佬更新了

**Comment by imebeh** [comment]
> 群晖升级3.0后web control失效了，小白也不敢瞎折腾，坐等大佬更新了

试过重装transmission-web-control吗，可能升级后index.html被覆盖了

**Comment by Joey0217** [comment]
> > 群晖升级3.0后web control失效了，小白也不敢瞎折腾，坐等大佬更新了
> 
> 试过重装transmission-web-control吗，可能升级后index.html被覆盖回原版了

谢谢大佬，回去从另一台群晖上复制过来试试，昨天因为忘了目录在哪，计划任务的链接被墙，后来放弃了……

**Comment by rootsun** [comment]
> 群晖升级3.0后web control失效了，小白也不敢瞎折腾，坐等大佬更新了

重装TWC就可以了，正如@imebeh 所说，只是升级后web目录内容被覆盖回原版了。

**Comment by Joey0217** [comment]
> > 群晖升级3.0后web control失效了，小白也不敢瞎折腾，坐等大佬更新了
> 
> 重装TWC就可以了，正如@imebeh 所说，只是升级后web目录内容被覆盖回原版了。

谢谢，已经重装恢复正常了～

**Comment by DarkAlexWang** [comment]
Closed this thread for inactivity.
