### ISSUE TITLE
希望能够添加一个按完成时间排序

### ISSUE THREAD

**Issue by ChiMuYuan** [ronggang/transmission-web-control#427]
希望能够添加按完成时间排序。

**Comment by imebeh** [comment]
右键点种子列表的表头，选上“完成时间”，再点表头的完成时间就可以按此排序

**Comment by ChiMuYuan** [comment]
@imebeh 不好意思，没有找到”完成时间“。与时间有关的排序只有”剩余时间“，”添加时间”，“最后活跃于”。 确实原版的webui也没有

**Comment by imebeh** [comment]
搜了一下提交记录，作者已经修过了，更新到最新版即可


提交记录：
https://github.com/ronggang/transmission-web-control/commit/ac3709c2d7be8ef083e9047244d452ff3d628b94#diff-2a03bd6dc9ab8c78cd9ef4c8a5507384
原issue #289

**Comment by db-one** [comment]
最新版不还是18年更新的v1.6.0-beta2吗？

**Comment by db-one** [comment]
看到了     src文件夹

**Comment by imebeh** [comment]
后面好像是没发release，装仓库版即可

**Comment by ChiMuYuan** [comment]
@imebeh 好的，非常感谢
