### ISSUE TITLE
可用空间：未知

### ISSUE THREAD

**Issue by yu4618** [ronggang/transmission-web-control#429]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: transmission-daemon 2.94
* Tr Web Control 版本: 1.6.0 beta
* 浏览器名称及版本：Google Chrome 版本 83.0.4103.116（正式版本） （64 位）
* 问题描述:

网页最底部的出现了“可用空间：未知”，我另一台服务器上是正常显示容量的，只有这台显示的“未知”。

--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by imebeh** [comment]
原版UI（在添加任务的页面）能显示得了吗

**Comment by yu4618** [comment]
> 原版UI（在添加任务的页面）能显示得了吗？

![image](https://user-images.githubusercontent.com/25944173/86535369-6a2ef400-bf12-11ea-8749-d900fd3a2b65.png)
原版的右侧下部这个不知道是系统的容量还是任务的容量，为none。

**Comment by yu4618** [comment]
随便添加个链接下载东西，过了一会儿就自己显示出来容量了。
😅
