### ISSUE TITLE
Cannot change queue order of files

### ISSUE THREAD

**Issue by ghost** [ronggang/transmission-web-control#43]
Hi,
I am running Transmission remotely from my NAS Qnap TS-212
Transmission version 2.84-b24

I discovered I cannot move anymore files in download queue (ie cannot move them "up" or "down" in queue)

Somebody can give a hint?

Thanks

**Comment by jeroenpeters1986** [comment]
This is indeed a confirmed bug, I think the ajax request to move it to the top does not send the appriopriate parameters

**Comment by DarkAlexWang** [comment]
#46
