### ISSUE TITLE
种子显示黄标感叹号 Tracker did not respond

### ISSUE THREAD

**Issue by RickyXwang** [ronggang/transmission-web-control#434]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmission版本: 3.00 (bb6b5a062e), RPC: 16
* Tr Web Control 版本:  1.6.0 beta (20180906)
* 浏览器名称及版本： Google Chrome 83.0.4103.116 (Official Build) (64-bit)
* 问题描述: 大部分种子显示黄标感叹号， Tracker did not respond, 或者 Tracker gave HTTP respond code 0 (no respond) 然而新加入的同个tracker种子尽管有警告，一段时间后仍能够获取到peer，在pt站显示上下行数量也是正常的。暂时不影响正常使用，但是满屏的黄标还是很难受。怀疑与Transmssion 3.0连接tracker的频率与次数有关。然而我并未找到调整此参数的方法。有些种子能在一段时间后显示正常，其他仍有警告。上述提到的种子全部在同一个PT站tracker下。
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 3.00 (bb6b5a062e), RPC: 16
* Tr Web Control version:  1.6.0 beta (20180906)
* Browser name & version： Google Chrome 83.0.4103.116 (Official Build) (64-bit)
* Problem description: Lots of torrents have a warning sign of "Tracker did not respond" or "Tracker gave HTTP respond code 0 (no respond)". However, the it still will be able to get peer after a while, the information is correct in the PT site. That being said although it does not affect normal use, it is still very annoying to see most of the torrents have yellow warning signs. Suspecting issue may be with how frequently Transmission 3.0 communicates with the Tracker. But I did not find how I can adjust that. Some torrents become normal in the interface after a day (20+ hr) or so, others still have the warning sign. All torrents mentioned above belong to the same PT site and under one tracker.

**Comment by imebeh** [comment]
是有tracker返回过错误信息，稳定之后刷新一下页面就好了

**Comment by RickyXwang** [comment]
只是做种的种子都恢复正常显示了，活动的种子（上传或下载）仍然会有警告。页面刷新过了。

**Comment by imebeh** [comment]
鼠标放在感叹号图标上是显示的什么？
如果都是分号话，下个版本就修复了（仓库的非min版代码已修复）
如果还有其他内容，可以考虑换掉那些连不上的tracker

**Comment by RickyXwang** [comment]
分号之前看到过，显示的是 Tracker did not respond, 或者 Tracker gave HTTP respond code 0 (no respond)，不过现在好像已经正常，期待下个版本更新。种子只有一个tracker。
