### ISSUE TITLE
请更新 checkupdate.js

### ISSUE THREAD

**Issue by coeusite** [ronggang/transmission-web-control#44]
在 src/tr-web-control/script/system.js 中调用了：
https://transmission-control.googlecode.com/svn/resouces/checkupdate.js

但是后者返回 404 Error。

**Comment by jeroenpeters1986** [comment]
Yes, this his to be moved to github static, it an old version on Google Code anyway. 
Confirmed bug

**Comment by DarkAlexWang** [comment]
#46
