### ISSUE TITLE
功能建议 显示正在连接的用户

### ISSUE THREAD

**Issue by cmmdwl** [ronggang/transmission-web-control#449]
可以吧原版ui能够显示的用户数据显示出来么
![image](https://user-images.githubusercontent.com/21263352/92604987-c2ec8580-f2e3-11ea-8230-24d31690bca7.png)
我想要这些数据也能够显示出来，能看传送ip

**Comment by imebeh** [comment]
有的，前几天还增加了显示ip国旗


https://github.com/ronggang/transmission-web-control/pull/443

**Comment by cmmdwl** [comment]
真好，我喜欢
