### ISSUE TITLE
undefined download folder

### ISSUE THREAD

**Issue by Meutledaron** [ronggang/transmission-web-control#45]
Hi,

Sometimes the download folder is set to "undefined" and file are downloaded into /undefined

![7dd3b4e4b69545c007a4dfc945c65366](https://cloud.githubusercontent.com/assets/18124029/23204905/6e23ee7e-f8e8-11e6-9ba0-6c2a8d93ecf6.png)

The folder are created automatically.

I haven't found how reproduce the bug voluntariamente.

**Comment by ronggang** [comment]
I'm sorry, so late to reply.
You can enter the path you want to save.
