### ISSUE TITLE
我发现transmission的缓存一个BUG，只要在页面修改了缓存，就会导致速度异常

### ISSUE THREAD

**Issue by 1265578519** [ronggang/transmission-web-control#454]
![image](https://user-images.githubusercontent.com/6442439/93016346-136d2700-f5f3-11ea-8a05-5d3879d58b00.png)

从2M改成512M，保存后就会这个样子
![image](https://user-images.githubusercontent.com/6442439/93016363-30095f00-f5f3-11ea-89e4-1a50093a943f.png)

![1](https://user-images.githubusercontent.com/6442439/93016389-6515b180-f5f3-11ea-966a-b694068ef13e.gif)

此时查看配置文件里面还是2M
vi /home/transmission/.config/transmission/settings.json

改动GUI上的缓存导致异常，修复方法只要重启客户端就行了
service transmissiond stop
service transmissiond start

**Comment by ronggang** [comment]
Tr 什么版本？

**Comment by 1265578519** [comment]
2.94

**Comment by yanlusu** [comment]
2.94，我在配置文件里改成256，过一段时间，进程直接挂了

**Comment by ronggang** [comment]
256 缓存设置有点大。不过我没遇到过速度会影响的情况。
