### ISSUE TITLE
升级到1.6.1版本后，查看种子属性，几乎全部为空白。

### ISSUE THREAD

**Issue by yanlusu** [ronggang/transmission-web-control#455]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.9.4
* Tr Web Control 版本: 1.6.1
* 浏览器名称及版本：chrome 85.0.4183.102
* 问题描述:
从1.6.0-beta2升级到1.6.1后，选中某一行种子记录，查看底部的种子属性，几乎所有的信息都是空白的，包括服务器信息、客户连接等等。
退回1.6.0-beta2后就OK
再更新到1.6.1就又看不到种子属性信息了。

--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by alxt17** [comment]
同样的问题，最新的web control1.6.1，tr版本是2.9.4，只有“常规”内有种子消息，“服务器”，“文件”，“用户”均为空白。

**Comment by yanlusu** [comment]
确定试过了可以？
我把chrome的缓存全部清空后，界面变成了几条线，连界面都出不来了。
又重装了两遍，依然如此。
另外，您的回复里说的“右键点击刷新”按钮，没找着，我是在设置里面全部清空的缓存。
“清空缓存并硬件重新加载”是个什么操作？

**Comment by harrison-guo-chn** [comment]
我也是，服务器和用户两栏都是空白内容

> 如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
> 
> * Transmssion 版本: 2.9.4
> * Tr Web Control 版本: 1.6.1
> * 浏览器名称及版本：chrome 85.0.4183.102
> * 问题描述:
>   从1.6.0-beta2升级到1.6.1后，选中某一行种子记录，查看底部的种子属性，几乎所有的信息都是空白的，包括服务器信息、客户连接等等。
>   退回1.6.0-beta2后就OK
>   再更新到1.6.1就又看不到种子属性信息了。
> 
> ## For English User
> Please provide the following information.
> 
> * Transmssion version:
> * Tr Web Control version:
> * Browser name & version：
> * Problem description:

尝试无痕页面打开后能显示内容，可以尝试一下，如果无痕浏览能显示就可以清楚缓存

**Comment by lePig** [comment]
先按下F12，然后在右键点击“刷新按钮”，然后就能看到了。
我也是这个问题，按照上面操作就好了。

**Comment by harrison-guo-chn** [comment]
> 确定试过了可以？
> 我把chrome的缓存全部清空后，界面变成了几条线，连界面都出不来了。
> 又重装了两遍，依然如此。
> 另外，您的回复里说的“右键点击刷新”按钮，没找着，我是在设置里面全部清空的缓存。
> “清空缓存并硬件重新加载”是个什么操作？
> ![截屏2020-09-14 上午9 34 24](https://user-images.githubusercontent.com/1924699/93034736-a3e84d80-f66d-11ea-96f4-cd6abbdab468.png)

先按f12，然后地址栏旁边那个刷新按钮右键就看到了

**Comment by yanlusu** [comment]
我是`macOS`，`F12`不是快捷键。
用如下方法解决了这个问题，本质还是清除本地缓存，应该是`javascript`脚本没有更新到最新版本。
0、关闭打开的`transmission web`页面；
1、点`Chrome`右上角那三个小点的图标；
2、“更多工具”->“清除浏览数据”；
3、除了历史浏览记录外的其他数据全部勾选上；
4、清除；
5、重新登录`transmission web`页面，就可以了。

**Comment by yanlusu** [comment]
谢谢各位的回复：）
