### ISSUE TITLE
1.6.1 用户列表无法显示国旗

### ISSUE THREAD

**Issue by prod428** [ronggang/transmission-web-control#457]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.94
* Tr Web Control 版本: 1.6.1
* 浏览器名称及版本：Chrome  85.0.4183.102
* 问题描述:在参数里设置了ipinfo的token，但用户列表里还是不能显示国旗

**Comment by ronggang** [comment]
应该是跨域问题，测试了一下，目前只有禁用跨域设置才可以正常显示。

**Comment by prod428** [comment]
> 应该是跨域问题，测试了一下，目前只有禁用跨域设置才可以正常显示。

谢谢~

**Comment by ronggang** [comment]
使用安装脚本，选 9 更新到最新代码应该可以正常工作了，如果无法显示，请检查是否被广告插件拦截了。

**Comment by prod428** [comment]
> 使用安装脚本，选 9 更新到最新代码应该可以正常工作了，如果无法显示，请检查是否被广告插件拦截了。

搞定了，adguard会屏蔽，把和ipinfo的规则取消就正常了
![image](https://user-images.githubusercontent.com/13960142/93292472-3fb5bd00-f818-11ea-941f-8a21236735e1.png)

**Comment by thomasho18** [comment]
可以請教一下如果要顯示國旗，是要做怎樣的設定?
IPinfo.io access token: 這邊需要填入甚麼嗎?

**Comment by prod428** [comment]
点击后面的感叹号~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "thomasho18"<notifications@github.com&gt;; 
发送时间: 2020年9月16日(星期三) 晚上10:52
收件人: "ronggang/transmission-web-control"<transmission-web-control@noreply.github.com&gt;; 
抄送: "ProD"<61211172@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [ronggang/transmission-web-control] 1.6.1 用户列表无法显示国旗 (#457)





 
可以請教一下如果要顯示國旗，是要做怎樣的設定?
 IPinfo.io access token: 這邊需要填入甚麼嗎?
