### ISSUE TITLE
1.6.1版本正在校验的种子进度条无法自动更新

### ISSUE THREAD

**Issue by Totobo** [ronggang/transmission-web-control#458]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.94
* Tr Web Control 版本: 1.6.1
* 浏览器名称及版本：Chrome 版本 85.0.4183.102（正式版本） （64 位）
* 问题描述: 校验已下载的种子目前可以看到进度条了，但是自动刷新的时候，种子校验页面的进度百分比无法同时更新，点击twc的刷新按钮也无法更新。只有刷新整个页面之后才会更新进度条。下载上传速度等其他信息定时刷新还是生效的

**Comment by imebeh** [comment]
@ronggang 应该是 transmission.torrent.min.js 没有更新

**Comment by ronggang** [comment]
> @ronggang 应该是 transmission.torrent.min.js 没有更新

嗯，看到了，时间戳没有改 😇

**Comment by ronggang** [comment]
看起来不是这个问题。

**Comment by imebeh** [comment]
min.js也要重新生成

**Comment by ronggang** [comment]
> min.js也要重新生成
嗯，我本地重新生成试了一下不行，我再看看是什么原因。

**Comment by imebeh** [comment]
> 嗯，我本地重新生成试了一下不行，我再看看是什么原因。

可能是缓存的原因，我这边用jscompress.com生成的可以用
不刷新校验进度是因为之前版本没有获取校验进度的数据

**Comment by ronggang** [comment]
> > 嗯，我本地重新生成试了一下不行，我再看看是什么原因。
> 
> 可能是缓存的原因，我这边用jscompress.com生成的可以用
> 不刷新校验进度是因为之前版本没有获取校验进度的数据

我的问题，我把两台测试机搞错了，一直在没有更新的那台上测试 🤣🤣
