### ISSUE TITLE
升级1.6.1后，查看服务器、文件、用户均空白

### ISSUE THREAD

**Issue by yechong** [ronggang/transmission-web-control#460]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 2.94
* Tr Web Control 版本: 1.6.1
* 浏览器名称及版本：Chrome 版本 85.0.4183.83（正式版本） （64 位）
* 问题描述: 升级1.6.1后，查看服务器、文件、用户均空白，升级前一切正常
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by cnsunyour** [comment]
+1

**Comment by Anyfc** [comment]
缓存吧，刚刚我的也是没有显示，强制刷新了一下，就显示了

**Comment by cnsunyour** [comment]
对的，本来我以为我已经强制刷新了一下，还出问题。刚才就跟了一帖，跟完帖我又试着强制刷新了一下，OK了。所以把跟帖删了。

**Comment by MiyouQ** [comment]
我重启了下主机正常了  惊喜的发现GBK的种子中文名不乱码了

**Comment by Cyberxxt** [comment]
> 缓存吧，刚刚我的也是没有显示，强制刷新了一下，就显示了

怎么强制刷新？我也是这个问题，手动刷新页面也无解。开无痕标签倒是可以显示，ie edge也可以只有chrome不行

**Comment by MiyouQ** [comment]
> > 缓存吧，刚刚我的也是没有显示，强制刷新了一下，就显示了
> 
> 怎么强制刷新？我也是这个问题，手动刷新页面也无解。开无痕标签倒是可以显示，ie edge也可以只有chrome不行

无痕能显示那就是CHROME的老问题了 CRTL+F5强制刷新 再不行进设置"Cookie 和网站数据"把对应地址的数据全清了

**Comment by Cyberxxt** [comment]
> > > 缓存吧，刚刚我的也是没有显示，强制刷新了一下，就显示了
> > 
> > 
> > 怎么强制刷新？我也是这个问题，手动刷新页面也无解。开无痕标签倒是可以显示，ie edge也可以只有chrome不行
> 
> 无痕能显示那就是CHROME的老问题了 CRTL+F5强制刷新 再不行进设置"Cookie 和网站数据"把对应地址的数据全清了

有效，谢谢大佬！
