### ISSUE TITLE
群晖无法通过wget下载github的资源

### ISSUE THREAD

**Issue by moonrailgun** [ronggang/transmission-web-control#474]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 
* Tr Web Control 版本: 
* 浏览器名称及版本：
* 问题描述:
群晖无法通过wget下载github的资源

github升级为tls1.2以后旧版的wget无法正常获取

出现如下错误

```
--2020-10-04 21:41:53--  https://github.com/ronggang/transmission-web-control/archive/master.tar.gz
Resolving github.com (github.com)... 13.229.188.59
Connecting to github.com (github.com)|13.229.188.59|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.
```

`ipkg`上的`wget-ssl`只有相关的`openssl`只有旧版的(0.9.8v 19 Apr 2012)。有没有什么办法可以解决这个问题？

或者可否把wget修改为curl?

--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

Synology cannot download resource of github through `wget`

The resource of it is github upgrade to tls1.2

In synology, throw error below:
```
--2020-10-04 21:41:53--  https://github.com/ronggang/transmission-web-control/archive/master.tar.gz
Resolving github.com (github.com)... 13.229.188.59
Connecting to github.com (github.com)|13.229.188.59|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.
```

the package in `ipkg` just have old version of `openssl` (0.9.8v 19 Apr 2012). Is any solution to resolve it?

Or just change it from `wget` to `curl`?

**Comment by ronggang** [comment]
如是系统层面的问题，可以考虑手工更新一下。

**Comment by moonrailgun** [comment]
已经是最新版本了。。。我没有办法解决这个问题，有没有什么比较好的解决方案？

**Comment by ronggang** [comment]
用国内源试试？
https://gitee.com/culturist/transmission-web-control

**Comment by moonrailgun** [comment]
Thanks, 非常nice. 使用gitee解决了。gitee不像github那样不支持tls1.1

建议写到wiki上

```bash
wget https://gitee.com/culturist/transmission-web-control/raw/master/release/install-tr-control-gitee.sh --no-check-certificate
```

**Comment by test-black** [comment]
群晖默认 wget 不支持 ssl
```shell
sudo -i
ipkg remove wget
ipkg install wget-ssl
```
