### ISSUE TITLE
有办法读出时区吗？设置某些功能需要，功能是调度时区的

### ISSUE THREAD

**Issue by 1265578519** [ronggang/transmission-web-control#485]
![image](https://user-images.githubusercontent.com/6442439/97745299-9f93c900-1b23-11eb-8cf2-13ce4bc49f83.png)

![image](https://user-images.githubusercontent.com/6442439/97745337-b0dcd580-1b23-11eb-91a6-61b0aaa6130b.png)

比如界面上可以显示服务器的时区，这样就能知道服务器当前是几点钟，，，这时候好设置限速时间

或者，，另个思路，transmission有办法设置配置文件，通知软件运行在什么时区吗，例如php.ini  my.cnf那样

**Comment by ronggang** [comment]
获取服务器时区应该可以，不过做起来得费点劲。
