### ISSUE TITLE
utp和upnp不是同一个东西，翻译错误

### ISSUE THREAD

**Issue by 1265578519** [ronggang/transmission-web-control#487]
![image](https://user-images.githubusercontent.com/6442439/97788153-b6a0ec80-1bf1-11eb-8c26-65264478eeb4.png)
![image](https://user-images.githubusercontent.com/6442439/97788163-c6b8cc00-1bf1-11eb-88e2-f724ccf7e472.png)

**Comment by pupboss** [comment]
@ronggang 他说的没错，端口转发那个实际是UPnP的功能，另外一个的功能可能要从RPC接口数据来看了
