### ISSUE TITLE
在种子校验界面，校验进度条在增加但数值未变动。

### ISSUE THREAD

**Issue by LoveU3th** [ronggang/transmission-web-control#490]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 3.00
* Tr Web Control 版本: 1.6.1_update1
* 浏览器名称及版本：Chrome V86.0.4240.111  
* 问题描述:    在种子校验界面，打开自动刷新，校验进度条在增加但百分比数值未变动。需手动刷新整个页面。

**Comment by shui** [comment]
同样的bug，可能是自动刷新页面失败的原因

**Comment by shui** [comment]
今天换到1.6.0 beta(20180906)，无此bug

**Comment by imebeh** [comment]
试试安装脚本第9项：安装最新代码库中的内容（master）

**Comment by shui** [comment]
> 试试安装脚本第9项：安装最新代码库中的内容（master）

确认已修复

**Comment by zhenmeiyin2** [comment]
安装脚本在哪呀？

**Comment by zhenmeiyin2** [comment]
> 
> 
> 试试安装脚本第9项：安装最新代码库中的内容（master）

管用，非常感谢！

**Comment by LoveU3th** [comment]
当前时间覆盖安装最新代码库内容可解决该问题，Close issue.
