### ISSUE TITLE
没有重命名功能

### ISSUE THREAD

**Issue by 1265578519** [ronggang/transmission-web-control#499]
![image](https://user-images.githubusercontent.com/6442439/100520196-82f8b880-31d7-11eb-9b89-15438502e54d.png)

原版GUI，设置名称就能改了
![image](https://user-images.githubusercontent.com/6442439/100520201-8c822080-31d7-11eb-9a66-ceda2bc872c1.png)

**Comment by imebeh** [comment]
菜单第三条“修改种子文件或目录名称”

**Comment by 1265578519** [comment]
> 菜单第三条“修改种子文件或目录名称”
这个功能对标是原版的设置下载位置，而不是重命名，是两个不同的功能，修改种子文件或目录名称也无法做到重命名的效果

**Comment by imebeh** [comment]
> 

我这边可以重命名，改下载位置在另外的地方

你用的是哪个版本

**Comment by 1265578519** [comment]
> > 
> 
> 我这边可以重命名，改下载位置在另外的地方
> 
> 你用的是哪个版本


![image](https://user-images.githubusercontent.com/6442439/100539939-f43a7900-3274-11eb-9a78-da292d244313.png)
Web Control: 1.6.1 (20200913) 最新的版本

**Comment by imebeh** [comment]
> Web Control: 1.6.1 (20200913) 最新的版本

奇怪了，我这边磁力链接、种子添加的任务、在下载的和已完成的等都可以正常用右键菜单的“修改种子文件或目录名称”来改名

而修改保存目录在菜单栏或者种子常规属性里面


你试试菜单栏的删除任务左边那个按钮（悬停会显示“修改种子文件或目录名称”）

**Comment by 1265578519** [comment]
> > Web Control: 1.6.1 (20200913) 最新的版本
> 
> 奇怪了，我这边磁力链接、种子添加的任务、在下载的和已完成的等都可以正常用右键菜单的“修改种子文件或目录名称”来改名
> 
> 而修改保存目录在菜单栏或者种子常规属性里面
> 
> 你试试菜单栏的删除任务左边那个按钮（悬停会显示“修改种子文件或目录名称”）

在哪。。有截图嘛

**Comment by imebeh** [comment]
右键菜单第三行……
第3行
第3⃣️行

**Comment by 1265578519** [comment]
> 右键菜单第三行……
> 第3行
> 第3⃣️行

....没看见，我瞎了，没和官方ui放在同一列贴在一起。。
