### ISSUE TITLE
种子下载完成后执行以下脚本功能重启失效

### ISSUE THREAD

**Issue by Mojelly** [ronggang/transmission-web-control#503]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 3.0
* Tr Web Control 版本: 1.61（20200913）
* 浏览器名称及版本：Chrome 87
* 问题描述: webUI设置中的”种子下载完成后执行以下脚本“功能，在transmission或者系统重启后失效，变回为没有勾选状态，请问是bug，还是现状如此？
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by ronggang** [comment]
这个倒是没有测试过，记得是读取transmission本身的参数，如果transmission没有保存，就会读取不到。

**Comment by yubanmeiqin9048** [comment]
同样的问题，只要重启web里的设置就会清空，应该是得把这个执行脚本写到TR的配置里
