### ISSUE TITLE
安装美化脚本本，依旧是原版皮肤。（Debain 10)

### ISSUE THREAD

**Issue by NiuXZi** [ronggang/transmission-web-control#507]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 最新版 (debain 10)
* Tr Web Control 版本: 最新版
* 浏览器名称及版本：edge( 87.0.664.60)
* 问题描述: 无法使用美化版，脚本检测tranmission未启动. 使用的是 hostsolutions 的512M的机子。
--------------------
## For English User 
Please provide the following information.
* Transmssion version: latest (debain 10)
* Tr Web Control version: latest 
* Browser name & version：edge ( 87.0.664.60)
* Problem description: Can't use the script. The script show me that cannot find the Tranmission which is running. 

状态码
`● transmission-daemon.service - Transmission BitTorrent Daemon
   Loaded: loaded (/lib/systemd/system/transmission-daemon.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-12-12 16:05:18 UTC; 3min 12s ago
 Main PID: 3861 (transmission-da)
   Status: "Idle."
    Tasks: 3 (limit: 540)
   Memory: 2.7M
   CGroup: /system.slice/transmission-daemon.service
           └─3861 /usr/bin/transmission-daemon -f --log-error

Dec 12 16:05:18 debian10 systemd[1]: Starting Transmission BitTorrent Daemon...
Dec 12 16:05:18 debian10 systemd[1]: Started Transmission BitTorrent Daemon.
Dec 12 16:05:19 debian10 transmission-daemon[3861]: [2020-12-12 16:05:19.449] UDP Failed to set receive buffer: requested 4194304, got 425984 (tr-udp.c:84)
Dec 12 16:05:19 debian10 transmission-daemon[3861]: [2020-12-12 16:05:19.450] UDP Failed to set send buffer: requested 1048576, got 425984 (tr-udp.c:95)`

**Comment by ronggang** [comment]
或许可以考虑一下手工更新一下。

**Comment by skygunner** [comment]
直接 cp -r 覆盖 web目录 + 修好权限

**Comment by NiuXZi** [comment]
在不断的反复重装后，莫名奇妙的可以了
