### ISSUE TITLE
easy install脚本不适用于群晖NAS DownloadStation套件

### ISSUE THREAD

**Issue by hitechbeijing** [ronggang/transmission-web-control#51]
不知道您是否有使用过群晖NAS，它的DownloadStation是基于transmission-daemon 2.84。此transmission并没有web目录。我修改了您的脚本，放在https://github.com/hitechbeijing/downloadstation-web-control
如果有必要可以和transmission-web-control项目做一个整合。

**Comment by DarkAlexWang** [comment]
可以啊，如果您有时间的话，能不能改一下您的easy_install.sh成easy_install_DS.sh之类的，放到release/ folder，然后提交个PR。
或者您有什么别的想法？

**Comment by iamcomet** [comment]
我这也有群晖，可以帮忙测试

2017年4月6日 00:04，"Alex Wang" <notifications@github.com>写道：

**Comment by hitechbeijing** [comment]
我改一份放你这整合一下，我自己那边单独放一份好了，既然建了就一直更新下去。其实还一个办法，通过uname -a判断一下是否是群晖，如果是则采取另外一种安装办法。这样一个脚本可以兼容普通服务器和群晖NAS。

**Comment by DarkAlexWang** [comment]
#54 Feature added.
