### ISSUE TITLE
“最大同时上传数”这个配置貌似是无效的。“最大同时下载数”是有效的。

### ISSUE THREAD

**Issue by CooperPro** [ronggang/transmission-web-control#512]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 3.00 (bb6b5a062e), RPC: 16
* Tr Web Control 版本: 1.6.1 (20200913)
* 浏览器名称及版本：87.0.4280.67（正式版本） (x86_64)
* 问题描述:如题。另外这个配置好像是对同时做种数生效，而不是同时上传数。不知道这算是bug，还是我的理解问题。不过希望有对同时活动上传数的配置功能。
* 
<img width="1679" alt="WX20210104-145027@2x" src="https://user-images.githubusercontent.com/76936179/103523557-fcf71e00-4eb6-11eb-9f35-bedc6c3329c9.png">

--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by CooperPro** [comment]
其实就是希望可以有一个配置，设置最多有几个种子有上传速度。

**Comment by CooperPro** [comment]
或者是像qb那样，支持设置”全局最大上传线程“或者”每种子最大上传线程“。
因为经常出现这种情况：全局有5、60个种子有上传速度，但是每个也就几kb到10几kb。这样不光上传速度不可观，而且硬盘负荷也很大。所以，最好能把所有上传带宽都集中到3、5个种子上。速度可观，硬盘负荷也小。

**Comment by CooperPro** [comment]
查了下他的配置文件，好像只有这么一项可配置
"upload-slots-per-torrent": 14, 每个种子上传连接数
好像没有全局最大上传连接数

**Comment by imebeh** [comment]
> 因为经常出现这种情况：全局有5、60个种子有上传速度，但是每个也就几kb到10几kb。这样不光上传速度不可观，而且硬盘负荷也很大。所以，最好能把所有上传带宽都集中到3、5个种子上。速度可观，硬盘负荷也小。

这个是transmission-daemon的活，应该到transmission那里提issue，ui上不好做的，即使做了也要24h开webui才有作用

可以设置个默认的分享率或者做种时没流量时间的限制，到了会自动暂停，需要长时间做种的再单独取消限制。
没有公网IP或者有公网IP没有做端口映射的主动连接过来的peer很少，分享率提高慢，很容易错过暂停条件

**Comment by cereushy** [comment]
强烈支持这个功能回归，不过我们应该跑到tr主程序那边去说。。。
在老版本里这个功能是存在的。
`2.31 (and older)
open-file-limit: Number (default = 32)`

可是被取消了，好像官方的说明是“系统已经提供了足够好的分配方案”。
总之，对于pter来说，几十个种子每个十几k上传还疯狂卡硬盘，真的蛋疼，支持这个功能

**Comment by CooperPro** [comment]
> 强烈支持这个功能回归，不过我们应该跑到tr主程序那边去说。。。 在老版本里这个功能是存在的。 `2.31 (and older) open-file-limit: Number (default = 32)`
> 
> 可是被取消了，好像官方的说明是“系统已经提供了足够好的分配方案”。 总之，对于pter来说，几十个种子每个十几k上传还疯狂卡硬盘，真的蛋疼，支持这个功能
