### ISSUE TITLE
一个建议，安装到/usr/share/transmission/web的子目录下

### ISSUE THREAD

**Issue by Cye3s** [ronggang/transmission-web-control#52]
比如plus子目录下，这样就不用去改名原始的index.html，也不会被Transmission更新所覆盖
然后访问地址改成http://test.com:9091/transmission/web/plus/index.html
js和html代码要做小修改，比如调用原始页面就改为../index.html，调用rpc部分改成../../rpc

我目前自己改了在用，不过每次更新transmission-web-control要自己改下

看到终于有人接手维护了，真好

**Comment by DarkAlexWang** [comment]
呵呵，谢谢支持。
我一般都是安装到VPS上的，然后安装完就没再升级过了，确实没遇到过您这样的烦恼。
要不再等等看，看看还有别人有这样的要求没有。
毕竟这样一改，可能大家以前保存的网址就都得重新修改。

**Comment by wgf0330** [comment]
还是不改的好，更新基本覆盖一次就行。

**Comment by xwlcn** [comment]
你这个建议真的坑爹，没看到提醒要用新地址，害我一直报index.html找不到，发现/usr/share/transmission/web里有个web，应该就是应用了你的建议，我手动copy出来竟然还不行（web虽然能进去了，设置全空白）！

**Comment by DarkAlexWang** [comment]
@xwlcn 跟他这个建议没关系，而且人家也是好意。

你的问题应该是哪个安装脚本的问题，实在不行，你先用回原来的版本，我这里有一个跟新之前的版本。你可以试一试好不好用。 也不知道你是用的DS还是普通的transmission
https://github.com/DarkAlexWang/transmission-web-control

**Comment by xwlcn** [comment]
@DarkAlexWang 我已经换回2014那个版本了，之前一直用的这个2014版本没任何问题，我装的是普通transmission.

**Comment by Cye3s** [comment]
莫名躺枪，哈哈哈
仓库里的代码都没变，实在不行，上面的同学就手动安装吧
如果这个项目一开始就按我说的那种方式，不动官方的index.html，就算安装脚本出问题，官方那页面还是能用的。现在大家都习惯了也不好改

**Comment by xwlcn** [comment]
我怀疑是代码更新出问题了，因为无论是https还是http的安装脚本，一个是嵌套了一个web目录 还有一个是和以前一样的，装完设置页面都是空白，看到右下角版本是2017的，之前用脚本安装都是2014的那个版本没任何问题，后来我copy以前装过的版本过去果然好了。
