### ISSUE TITLE
自动显示种子属性

### ISSUE THREAD

**Issue by shNanChen** [ronggang/transmission-web-control#53]
如果勾选“自动显示种子属性”，再单击任一种子，就会当前种子属性，
但是，会在自动刷新时间后被刷新掉，又不显示了。

目前在用 WEB Control: 0.6 Beta(20130913)，此版本表现正常，
之后的版本包括最新的，都存在上面的问题。

**Comment by DarkAlexWang** [comment]
确实是个bug，我看了下，暂时还找不到什么地方出错了，看看有没有其他朋友能找到问题在哪。

**Comment by DarkAlexWang** [comment]
@balonik Really appreciate your help here. Do you have time to submit a pull request. If you dont have time, please just let me know, I can make the change on your behalf.

**Comment by shNanChen** [comment]
试了 ce432982d3b90a4fd40db471e7ced8a0b5560cda ，“自动显示种子属性” 应该是修复了，挺好。

我自己尝试只替换 ce432982d3b90a4fd40db471e7ced8a0b5560cda 中 src/tr-web-control/script/system.js，貌似没效果，不明白。

**Comment by giveup** [comment]
@shNanChen 应该要替换两个,还有一个是 system.min.js .

**Comment by DarkAlexWang** [comment]
Problem should be solved for now. ad01081eba44123920a2edd2905957e26ff805e2
