### ISSUE TITLE
群晖使用install-tr-control-cn.sh脚本安装失败，安装路径判断有误切无法指定

### ISSUE THREAD

**Issue by msyzzm** [ronggang/transmission-web-control#555]
* Transmssion 版本: 2.93-14
* Tr Web Control 版本: v1.6.1-update1
* 浏览器名称及版本：Edge
* 问题描述: 群晖使用install-tr-control-cn.sh脚本安装失败，原因是脚本中的一个判断导致ROOT_FOLDER错误，而且尝试了使用指定安装目录的功能也无法改变这个目录。
* 比如我的路径应该是/volume1/@appstore/transmission/share/transmission，我把下面的判断里的路径修改成自己的就可以安装成功了。
 `	# 群晖
	if [ -f "/etc/synoinfo.conf" ]; then
		 @ROOT_FOLDER="/var/packages/transmission/target/share/transmission"
	fi`

**Comment by zhuqh93** [comment]
如何解决这个问题，没看懂，可否详细解释一下，thanks

**Comment by DarkAlexWang** [comment]
应该就是更改了一下安装的默认路径。谢谢反馈

**Comment by zhuqh93** [comment]
自己改？怎么改？不是应该作者更新git上的脚本吗

**Comment by msyzzm** [comment]
> 应该就是更改了一下安装的默认路径。谢谢反馈

是的，但是执行脚本内的指定路径功能也没有用，需要改脚本才行，这样是不是有问题？

**Comment by DarkAlexWang** [comment]
两个解决办法：1. 你自己fork，然后随便改。
2. 提交PR，没问题的话，我可以merge。但是抱歉，我没时间改。
