### ISSUE TITLE
群晖脚本安装失败

### ISSUE THREAD

**Issue by 1294266616** [ronggang/transmission-web-control#572]
tr版本 3.00-19
群晖版本 DSM 6.2.3-25426
出现下方这个错误
cp: cannot stat '/tmp/tr-web-control/transmission-web-control/src/.': No such file or directory
求大佬看看
附上日志文件
[install-tr-control-cn-log.txt](https://github.com/ronggang/transmission-web-control/files/7248691/install-tr-control-cn-log.txt)

**Comment by minnyres** [comment]
应该是打包的问题：
https://github.com/ronggang/transmission-web-control/issues/559
