### ISSUE TITLE
Tr Web Control在群晖NAS里通过计划任务执行安装成功，但访问失败，网页显示不出来就两个输入框，其他的都是空白

### ISSUE THREAD

**Issue by ptlzx57** [ronggang/transmission-web-control#573]
* 问题描述:
--------------------
Tr Web Control在群晖NAS里通过计划任务执行安装成功，但访问失败，网页显示不出来就两个输入框，其他的都是空白

Transmssion 版本: 3.00-19
Tr Web Control 版本: 1.6.1-update1
Safari浏览器 版本15.0 (16612.1.29.41.4, 16612)
/bin/whoami
--2021-10-05 12:03:22--  https://gitee.com/api/v5/repos/culturist/transmission-web-control/releases/latest
Resolving gitee.com... 180.97.125.228
Connecting to gitee.com|180.97.125.228|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4857 (4.7K) [application/json]
Saving to: 'STDOUT'

     0K ....                                                  100% 36.5M=0s

2021-10-05 12:03:22 (36.5 MB/s) - written to stdout [4857/4857]

<< 2021-10-05 12:03:22 >> == 开始 ==
<< 2021-10-05 12:03:22 >> 
<< 2021-10-05 12:03:22 >> 当前 Transmission Web 目录为:  /var/packages/transmission/target/share/transmission/web
<< 2021-10-05 12:03:22 >> 您正在使用指定版本安装，版本： 1.6.1-update1
<< 2021-10-05 12:03:22 >> 正在尝试指定版本 1.6.1-update1
<< 2021-10-05 12:03:22 >> 正在下载 Transmission Web Control...

--2021-10-05 12:03:22--  https://gitee.com/culturist/transmission-web-control/repository/archive/v1.6.1-update1.tar.gz
Resolving gitee.com... 180.97.125.228
Connecting to gitee.com|180.97.125.228|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://gitee.com/culturist/transmission-web-control/repository/blazearchive/v1.6.1-update1.tar.gz?Expires=1633407780&Signature=Mea%2BDZefC1LZEidteb3NmGD3ZLyJyvGWhxQBFLEnWFA%3D [following]
--2021-10-05 12:03:23--  https://gitee.com/culturist/transmission-web-control/repository/blazearchive/v1.6.1-update1.tar.gz?Expires=1633407780&Signature=Mea%2BDZefC1LZEidteb3NmGD3ZLyJyvGWhxQBFLEnWFA%3D
Reusing existing connection to gitee.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-compressed-tar]
Saving to: 'v1.6.1-update1.tar.gz'

     0K .......... .......... .......... .......... ..........  479K
    50K .......... .......... .......... .......... ..........  363K
   100K .......... .......... .......... .......... ..........  482K
   150K .......... .......... .......... .......... ..........  481K
   200K .......... .......... .......... .......... ..........  483K
   250K .......... .......... .......... .......... ..........  490K
   300K .......... .......... .......... .......... ..........  515K
   350K .......... .......... .......... .......... ..........  627K
   400K .......... .......... .......... .......... ..........  532K
   450K .......... .......... .......... .......... ..........  724K
   500K .......... .......... .......... .......... ..........  518K
   550K .......... .......... .......... .......... ..........  733K
   600K .......... .......... .......... .......... ..........  700K
   650K .......... .......... .......... .......... ..........  730K
   700K .......... .......... .......... .......... ..........  736K
   750K .......... .......... .......... .......... ..........  729K
   800K .......... .......... .......... .......... ..........  744K
   850K .......... .......... .......... .......... ..........  727K
   900K .......... .......... .......... .......... ..........  789K
   950K .......... .......... .......... .......... ..........  739K
  1000K .......... .......... .......... .......... ..........  745K
  1050K .......... .......... .......... .......... .......... 1.02M
  1100K .......... .......... .......... .......... ..........  898K
  1150K .......... .......... .....                             760K=1.9s

2021-10-05 12:03:25 (616 KB/s) - 'v1.6.1-update1.tar.gz' saved [1203986]

<< 2021-10-05 12:03:25 >> 下载完成，正在准备安装...
<< 2021-10-05 12:03:25 >> 正在解压安装包...
<< 2021-10-05 12:03:25 >> 正在复制安装包...
cp: cannot stat '/tmp/tr-web-control/transmission-web-control/src/.': No such file or directory
<< 2021-10-05 12:03:25 >> 正在设置权限，大约需要一分钟 ...
<< 2021-10-05 12:03:26 >> Transmission Web Control 安装完成!
<< 2021-10-05 12:03:26 >> 正在清理安装包...
<< 2021-10-05 12:03:26 >> 安装脚本执行完成。如遇到问题请查看：https://github.com/ronggang/transmission-web-control/wiki 
<< 2021-10-05 12:03:26 >> == 结束 ==

**Comment by Yumerakk** [comment]
请问解决办法是什么，我清除缓存后没用

**Comment by cerellean** [comment]
我也经常性碰到
感觉就是运气问题，时好时坏
