### ISSUE TITLE
下载目录列表可以支持自定义吗

### ISSUE THREAD

**Issue by shootheart** [ronggang/transmission-web-control#576]
我发现我的下载目录列表里好多是重复的路径，就像下面这样
没有找到哪里可以修改或删除列表项的
![image](https://user-images.githubusercontent.com/16322379/138563952-48160981-ec9c-40ae-9a6d-2170901424b5.png)
希望关注一下，谢谢

**Comment by fengqi** [comment]
这个是从已有的任务里提取的，或者是在 `设置-目录字典` 里定义的。
手动输入的时候有时候结尾有 `/` 有时候没有，就会显示两个，建议可以对目录结尾 `/` trim 然后去重。

**Comment by fengqi** [comment]
@shootheart  我提交了一个pull request，你如果着急可以按我的修改，自己改下指定的文件，就可以去重了。

**Comment by fengqi** [comment]
@shootheart  我提交的改动已经合并，建议使用最新代码，并关闭这个issue。
