### ISSUE TITLE
默认保存目录不更新，与settings.json里的下载路径不一致

### ISSUE THREAD

**Issue by dongxi8** [ronggang/transmission-web-control#593]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: Transmission: 3.00 (bb6b5a062e), RPC: 16。安装在威联通的NAS里

* Tr Web Control 版本: Web Control: 1.6.1 (20200913)

* 浏览器名称及版本：chrome，98.0.4758.102
* 问题描述: 
<img width="207" alt="image" src="https://user-images.githubusercontent.com/1157840/156203465-2b57ea12-2bc4-4325-8f56-440605c00012.png">

<img width="305" alt="image" src="https://user-images.githubusercontent.com/1157840/156203576-d6f01cc9-ea7e-4785-9757-9c37cc276781.png">

--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by Trim21** [comment]
+1 似乎这个错误的默认的保存路径是受到现在列表种子影响的，一定会显示某个种子的下载路径。

但是跟rpc返回的下载目录不一样。

**Comment by kfstorm** [comment]
+1

我使用sonarr、radarr、lidarr来管理我的下载，所有的文件都会下载到子目录里。每次打开设置，在下载目录那里只显示几个子目录，不显示实际配置里的父目录。如果这时候修改一个其他的配置，保存后下载目录就会被误更新为某个子目录，然后我还得去原版UI里把下载目录改回父目录。

**Comment by trim21** [comment]
提的PR维护者一直没合并，我在 https://github.com/transmission-web-control/transmission-web-control 里修复了
