### ISSUE TITLE
好像新版添加种子有问题

### ISSUE THREAD

**Issue by wgf0330** [ronggang/transmission-web-control#61]
好像新版添加种子有问题
今天刚更新的

**Comment by wgf0330** [comment]
![0413c](https://cloud.githubusercontent.com/assets/18156721/24984793/609af44e-2022-11e7-8bdc-04e25aa542d8.png)

**Comment by DarkAlexWang** [comment]
我这边试了下，添加种子倒是正常，但是那个保存目录不知道为什么现在一直是undefined，改了以后再打开还是undefined。

**Comment by wgf0330** [comment]
我这边添加种子就卡在截图画面。3月31的版本倒是没问题，不知道怎么回退，找不到下载地址

**Comment by DarkAlexWang** [comment]
想问下，你有没有在保存目录那里把undefined改成你的下载路径。如果像上图一样是undefined的话是没法加载种子的。

**Comment by wgf0330** [comment]
没有，因为第一次出现，并不清楚是这个的问题，我等下试试看

**Comment by wgf0330** [comment]
修改之后可以了。谢谢

**Comment by wgf0330** [comment]
另外，每次更新能不能把日期和版本也一起变化一下，我刷新了很多次没变化，还以为更新没成功，重启才确认是版本没变化

**Comment by DarkAlexWang** [comment]
不客气，不过那个下载地址没法保存的毛病还是挺烦人的。
好的，以后会注意改一下版本号和时间的。
说实话我自己用的下载机上的这个软件从装过以后就没再跟新过，估计还是两年前的版本，一直觉得够用就行了。。。。

**Comment by Warden630** [comment]
确实是有问题，每次都必须手动写种子地址

**Comment by DarkAlexWang** [comment]
可以在设置里的"Folder Dictionary"加上你的地址，下次打开就可以自动加载那个地址了。
