### ISSUE TITLE
有没有附带帐号密码参数实现略过登录对话框？

### ISSUE THREAD

**Issue by kidzgy** [ronggang/transmission-web-control#610]
首次运行浏览器，浏览transmission时，都会弹出帐号密码的填写对话框，这个对话框麻烦的就是不是网址内的表单，没有办法借助javascript脚本实现填单，如果网址直接附带帐号密码参数，不知道能否实现免登录窗口直接登录呢？
比如网址附加[?user=1&?pwd=2]，即表示用户名1，密码2登录，直接略过帐号密码输入打开transmission。

**Comment by jinhang1997** [comment]
请将http基本验证的用户名密码直接写入URL
https://username:password@example.com:11111/transmission/web/

**Comment by kidzgy** [comment]
> 请将http基本验证的用户名密码直接写入URL https://username:password@example.com:11111/transmission/web/

原来如此，这个牛逼！

**Comment by maicss** [comment]
> > 请将http基本验证的用户名密码直接写入URL https://username:password@example.com:11111/transmission/web/
> 
> 原来如此，这个牛逼！

如果解决了问题，就关了这个issue吧
