### ISSUE TITLE
Transmission 4.0.0 失效 | transmission-web-control not working with Transmission 4.0.0

### ISSUE THREAD

**Issue by bianyukun1213** [ronggang/transmission-web-control#614]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 4.0.0
* Tr Web Control 版本: 1.6.1
* 浏览器名称及版本：Mozilla Firefox 109.0.1
* 问题描述: 升级到 4.0.0 后，Transmission 不再使用 transmission-web-control 作为 Web Client。这可能是因为 Transmission 4.0.0 重写了 Web Client。现在似乎会使用 `public_html` 下的文件作为 Web Client。
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 4.0.0
* Tr Web Control version: 1.6.1
* Browser name & version：Mozilla Firefox 109.0.1
* Problem description: After upgrading to version 4.0.0, Transmission does not use transmission-web-control as its Web client anymore. This is probably because of the rewrite of the Web client in version 4.0.0. It seems that Transmission 4.0.0 uses files under the folder `public_html` as its Web client currently.

**Comment by voodka** [comment]
我在4.0下用上传src文件到public_html目录的方法安装成功了，参考安装教程里Windows下的安装方法就行。
![image](https://user-images.githubusercontent.com/13945856/217981826-c1f014b7-4b15-459d-8eb7-43a788dd9c06.png)

**Comment by bianyukun1213** [comment]
> 我在4.0下用上传src文件到public_html目录的方法安装成功了，参考安装教程里Windows下的安装方法就行。 ![image](https://user-images.githubusercontent.com/13945856/217981826-c1f014b7-4b15-459d-8eb7-43a788dd9c06.png)

好的，谢谢！
