### ISSUE TITLE
安装web control后，原版UI无法使用

### ISSUE THREAD

**Issue by zhjh0521** [ronggang/transmission-web-control#618]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 4.0.0
* Tr Web Control 版本: 1.6.1
* 浏览器名称及版本：Chrome 110
* 问题描述: 成功安装了web control，UI也都可以使用。但界面里的“原版UI”点击后会提示找不到index.original.html

/transmission-web-control/web/index.original.html (No such file or directory)

地址栏是：http://x.x.x.x:9091/transmission/web/index.original.html

这个原版的html页面在哪里啊？怎么解决这个问题呢，谢谢

**Comment by Xdynix** [comment]
参考Windows的3.0.0 -> 4.0.0升级变化，新的安装路径应该是先把/transmission-web-control/public_html/index.html重命名成index.original.html，然后把web ui的内容复制到/transmission-web-control/public_html下。

**Comment by zhjh0521** [comment]
> 

我之前确实没有重命名，直接覆盖了，你有原版的index.html吗？能不能发一个给我

**Comment by Xdynix** [comment]
[index.original.html.zip](https://github.com/ronggang/transmission-web-control/files/10953959/index.original.html.zip)

**Comment by zhjh0521** [comment]
> [index.original.html.zip](https://github.com/ronggang/transmission-web-control/files/10953959/index.original.html.zip)

谢谢。用你的方法可以了，但这个页面是3.0的原版UI吧。我在docker的环境变量里的TRANSMISSION_WEB_HOME这个删掉，默认就回到了4.0的界面，是这个样子的

看起来还是有默认的index.html的，就是不知道在哪里

**Comment by zhjh0521** [comment]
奇怪，上传图片失败了

**Comment by Xdynix** [comment]
我是今天才刚刚升级的4.0，之前上传的应当是4.0的index.html。我没有试过docker安装，就不确定了。其他issue也有讨论docker的升级的。

**Comment by zhjh0521** [comment]
> 

完蛋了，我现在怎么搞也搞不好原版UI了，连3.0的也搞不出来了。但去掉docker的环境变量TRANSMISSION_WEB_HOME，原版UI还是能工作的。不知道有没有知道，docker里面原版的UI文件在哪里

**Comment by imebeh** [comment]
- 可以从这里下载原版4.0的webUI `https://github.com/transmission/transmission/tree/main/web/public_html`，或者[release的源码](https://github.com/transmission/transmission/archive/refs/tags/4.0.1.zip)
- 把 `index.html` 改名为 `index.original.html`
- 复制到 transmission-web-control 所在文件夹，合并两个web UI（index.html 改名了，所以应该不存在同名文件）
- `TRANSMISSION_WEB_HOME` 指定web UI 位置

**Comment by zhjh0521** [comment]
> * 可以从这里下载原版4.0的webUI `https://github.com/transmission/transmission/tree/main/web/public_html`，或者[release的源码](https://github.com/transmission/transmission/archive/refs/tags/4.0.1.zip)
> * 把 `index.html` 改名为 `index.original.html`
> * 复制到 transmission-web-control 所在文件夹，合并两个web UI（index.html 改名了，所以应该不存在同名文件）
> * `TRANSMISSION_WEB_HOME` 指定web UI 位置

非常感谢，搞定了！！！
