### ISSUE TITLE
群晖套件中心版本4.0.2 web-ui失效

### ISSUE THREAD

**Issue by jt8823** [ronggang/transmission-web-control#621]
如果反馈BUG，请提供以下信息，如果可能，同时提供英文描述，谢谢。
* Transmssion 版本: 4.0.2
* Tr Web Control 版本: 最新
* 浏览器名称及版本：edge
* 问题描述: 4.0.2版本安装后,还是原版UI   是需要调整什么吗?
--------------------
## For English User 
Please provide the following information.
* Transmssion version: 
* Tr Web Control version: 
* Browser name & version：
* Problem description:

**Comment by jt8823** [comment]
已解决  谢谢

**Comment by fangbq** [comment]
> 

请问怎么解决的

**Comment by jt8823** [comment]
> 请问怎么解决的
https://github.com/ronggang/transmission-web-control/issues/620#issuecomment-1486710925

**Comment by fangbq** [comment]
> > 请问怎么解决的
> > [#620 (comment)](https://github.com/ronggang/transmission-web-control/issues/620#issuecomment-1486710925)

奇怪，我ls -lt后看不到第二条 .... web

**Comment by wu0lei** [comment]
已解决 谢谢

**Comment by magic-monkey** [comment]
根据https://github.com/ronggang/transmission-web-control/issues/620#issuecomment-1486710925这条输入命令无法执行
