### ISSUE TITLE
x86_64 群晖系统+EntWare的Transmission 2.92安装问题

### ISSUE THREAD

**Issue by zeroxia** [ronggang/transmission-web-control#76]
在一个老笔记本上安装了一个群晖6.0.2，然后用了EntWare，安装的 transmission-daemon 版本为 2.92，一些问题罗列如下：

1、EntWare用 opkg install transmission-web 后，web相关文件所在 路径是 /opt/share/transmission/web 而不是在 /usr/local/share 下，如果按照这里的 DiskStation 的安装脚本来做，是不是会无法调用到？

2、我自己把脚本里提到的 full package 和 old package 都下载回来合在了一起，然后放到了 /opt/share/transmission/web 下，可以打开网页进行管理。但是 config 配置界面有点问题，点击配置按钮，出来的都是空白。如下图：

![blank config](http://wx2.sinaimg.cn/large/61260048gy1feohehg1hpj20ia0d1q30.jpg)

然后我打开了 original UI ，做了一下速度限制的配置，再回到这个新的 UI ，然后点击配置，居然配置界面就出来了，但是在最后一个配置页“Folders Dictionary”，显示的是 undefined，这是正常的吗？

![undefined folders directory](http://wx3.sinaimg.cn/large/61260048gy1feohei0gh2j20hv0cqaa7.jpg)

我后来重新打开了一个浏览器（Chrome New Incognito Window），像再尝试一下那个配置界面从无到有的过程，但是没有成功。

**Comment by yeeteck** [comment]
我的也是 我是手动安装 界面是成功 config界面空白
然后就用回ds...

**Comment by yeeteck** [comment]
我第一架群晖上个月安装 手动安装没问题 我相信应该是最近几天升级了就变这样

**Comment by DarkAlexWang** [comment]
@zeroxia 
1. 不会的，@hitechbeijing 对DS的安装脚本进行了修改，会对DS的安装路径进行判别。当然我也没试过，具体情况我也不太清楚。
2. 最后一个配置页“Folders Dictionary”，显示的是 undefined，这是正常的, 你可以自行修改。

**Comment by DarkAlexWang** [comment]
请更新到最新版，应该是没有问题了。
