### ISSUE TITLE
最新版bug

### ISSUE THREAD

**Issue by cherishwee** [ronggang/transmission-web-control#77]
首先感谢作者为大家辛苦制作，我安装的是transmission2.77，使用一件脚本安装最新版的控制器后，无法修改transmission的设置，而且也不能电脑添加种子，因为保存路径是空的，且没办法手动填写。截图
http://image18-c.poco.cn/mypoco/myphoto/20170420/15/18394931520170420151418051.jpg
http://image18-c.poco.cn/mypoco/myphoto/20170420/15/18394931520170420151328068.jpg

手机版一切正常。

**Comment by DarkAlexWang** [comment]
临时的解决办法： 
“然后我打开了 original UI ，做了一下速度限制的配置，再回到这个新的 UI ，然后点击配置，居然配置界面就出来了”
或者您更新下transmission的版本看看。

**Comment by cherishwee** [comment]
谢谢，我什么都没有操作，自动神奇的好了。
也不知道哪个transmission稳定，大神，推荐个稳定版本吧

**Comment by yeeteck** [comment]
临时的解决办法：
“然后我打开了 original UI ，做了一下速度限制的配置，再回到这个新的 UI ，然后点击配置，居然配置界面就出来了”
或者您更新下transmission的版本看看。

试了重新安装还是不行
按原装界面 去设置 回去新界面还是一样空白
版本dsm6.1-update2 tr2.92-synocommunity安装的

-或到下载安装脚本，此脚本只需要下载一次，以后只需要执行即可:
-如果需要http而不是https，请使用以下命令:
安装上面2个..手动安装 全部是界面成功 设置页面空白
![capture](https://cloud.githubusercontent.com/assets/27337585/25246111/35d3c6f6-2639-11e7-98e0-2892745800ee.PNG)
![capture2](https://cloud.githubusercontent.com/assets/27337585/25246115/390859e0-2639-11e7-848a-05e2c075b03d.PNG)

**Comment by yeeteck** [comment]
谁有旧的上个版本可以连接一下 谢谢

**Comment by DarkAlexWang** [comment]
@yeeteck 你试试这个repo，https://github.com/hitechbeijing/downloadstation-web-control，貌似他还没有跟新到最新版。
@cherishwee 好神奇，版本无所谓，能用就行了。

**Comment by yeeteck** [comment]
@DarkAlexWang 你试试这个repo，https://github.com/hitechbeijing/downloadstation-web-control
貌似他还没有跟新到最新版。

感谢 安装成功 设置页面有了
谢谢大大

**Comment by xwlcn** [comment]
不先是网页大都打不开吗？他的web解压到了/usr/share/tranmission/web目录里面去了 相当于嵌套了一层，copy出来才发现设置什么的全是空白！！！

**Comment by zelywind** [comment]
同样的问题，获取不到下载目录导致 设置界面全部空白【如yeeteck的截图】，当我点击设置按钮时出现“VM4960:143 Uncaught TypeError: Cannot read property 'length' of undefined”的错误，143行	if (system.dictionary.folders.length!=0)，出错的提示是使用F12工具查看的。希望尽早修复。

**Comment by DarkAlexWang** [comment]
@xwlcn @zelywind 我跟新了安装文件，安装目录嵌套的问题应该解决了，设置菜单不显示的问题应该改过来了。麻烦大家有时间的话再测试下。
不过设置菜单里的“缓存”那一栏还是没法正常显示宽度，还有以前是勾选某个选项就可以直接修改参数，现在不行了，必须要保存以后才能更改了。大家谁如果知道问题在哪，麻烦告诉我，谢谢。

**Comment by wgf0330** [comment]
感谢更新，暂时没发现问题，加载速度似乎也有所提高

**Comment by wgf0330** [comment]
补充一下，每页最大显示种子数目能不能该大一下，现在最多50，可以最大改成100-200吗

**Comment by yeeteck** [comment]
发现小问题
最新版的 加载种子时每次设置位置是空白的 不能打字 但是设置里的文件夹位置和folder dictionary是正确的
每次加载需要去设置按确定后 才能去加载种子 设置位置才会出现正确的位置

**Comment by pigpigabc123** [comment]
@yeeteck 发现小问题
最新版的 加载种子时每次设置位置是空白的 不能打字 但是设置里的文件夹位置和folder dictionary是正确的
每次加载需要去设置按确定后 才能去加载种子 设置位置才会出现正确的位置
这问题不知道是否是我个人才有

同样的问题，重启后第一次打开web页面 上传种子时保存位置是空白的，无法上传种子，必须点确定再打开才行

**Comment by yeeteck** [comment]
旧版没问题 但是种子加到第二页时 每次6-8秒又会自动跑去第一页 查看种子很不方便

上个版本 就是设置页面空白 不能设置

现在最新的 加载种子位置出现问题
希望alex大哥能出个较稳定版本 可以用 不用一直换版本 一不小心系统出错 就哭死了nas里面很多储存的

**Comment by DarkAlexWang** [comment]
@yeeteck  @pigpigabc123 我建议你们可以用回以前比较老的版本，我自己VPS上用的是几年前的版本。现在的问题主要是有一次跟新对Folder进行了变动，我大概知道问题在哪，可惜我javascript不怎么行，一时半会儿真是不知道怎么改，除了全改回原来的我也没什么好办法。
最近我在准备毕业的事情，忙完这段时间我再看看吧。

**Comment by yeeteck** [comment]
@DarkAlexWang 请问可以告诉我你用的版本吗 我上网找找 或者发个链接下载

**Comment by DarkAlexWang** [comment]
@yeeteck https://github.com/ronggang/transmission-web-control/tree/94a633e7b6b651f658be83ead0cfdd90c7c102fd
这是以前的老版本，你可以下载下来tar 文件，解压覆盖进你的目录就可以了。
看来以后有必要搞个stable版本和develop版本。

**Comment by DarkAlexWang** [comment]
@yeeteck @pigpigabc123 我试着在设置那里点一下确定，然后就能正常加载种子地址了，不知道你们是不是这种情况，如果是这样的话貌似也还好。

至于那个种子界面几秒钟后加载回第一个页面的问题，我这边没有。不太确定是什么原因。

**Comment by yeeteck** [comment]
@DarkAlexWang 
幸苦了你 谢谢
可以搞个stable版本和新版本
等2-3个月没什么问题 再把新版本放入stable里

**Comment by yeeteck** [comment]
@fdar0536 
下载最新版 解压transmission-control-full.tar.gz 丢进web里
应该就解决了

**Comment by fdar0536** [comment]
@yeeteck 我現在用的就是最新版

**Comment by DarkAlexWang** [comment]
感谢 @balonik 提供的修改方案，暂时应该修改好了。抱歉给大家带来的不便。
