### ISSUE TITLE
20170518版统计显示类BUG汇报

### ISSUE THREAD

**Issue by lottelucky** [ronggang/transmission-web-control#81]
此BUG好像在0504、0317中都存在
直至今天有点受不了了，所以汇报
【现象】左侧导航区，“全部”位置的右侧的种子容量显示错误，比如我现在同时有385个种子，而种子总容量只显示为3.33GB（显然不可能啊，基本上都是原盘），而且这个数字貌似一直会变，但都是错误的

**Comment by DarkAlexWang** [comment]
感谢支持和提意见。现在应该好了。
