### ISSUE TITLE
【建议】种子列表数是否可以改为可配置

### ISSUE THREAD

**Issue by lottelucky** [ronggang/transmission-web-control#82]
30-50，每次都要翻页
最多50，像我400多个种子，翻页仍然很麻烦
是否要以在设置中增加自定义，如果负荷允许，是否要以设置为ALL？

**Comment by DarkAlexWang** [comment]
@balonik 刚更新完是对的，后来种子列表数就变成单行了
![image](https://www.z4a.net/images/2017/05/23/snipaste_20170522_233036.png)

**Comment by balonik** [comment]
what browser? I have
FF 53
![image](https://cloud.githubusercontent.com/assets/17492066/26342425/50149c84-3f98-11e7-8293-3188960ccbd2.png)
Chromium 56
![image](https://cloud.githubusercontent.com/assets/17492066/26342469/8732175a-3f98-11e7-82e8-3cd56052540d.png)

**Comment by lottelucky** [comment]
能否默认显示为ALL

**Comment by balonik** [comment]
@lottelucky 
edit the config.js and change "pagination: true" to "pagination: false"

**Comment by balonik** [comment]
@DarkAlexWang 
https://github.com/balonik/transmission-web-control/commit/727a80899fe6fff655cdaf60733cc7865e76ea69

**Comment by DarkAlexWang** [comment]
@balonik I have FF 53. I got one error after implemented your new fix 727a808.
Not sure if you have the same problem or not.
![image](https://www.z4a.net/images/2017/05/23/snipaste_20170523_112607.png)

**Comment by balonik** [comment]
@DarkAlexWang 
just remove the transmission-web cookie from FF
I didn't put backward compatibility there.

**Comment by DarkAlexWang** [comment]
@balonik @lottelucky 
thanks, this should be ok now.

**Comment by Anyfc** [comment]
@balonik @DarkAlexWang 种子属性里面的文件显示 是否也可以显示得多一些，
一个大包里面有几千个文件，而我只想下载其中的几个文件，现在每页最多显示50，太少，翻页起来太累

**Comment by balonik** [comment]
https://github.com/balonik/transmission-web-control/commit/787612c1ef929fbbc183f4ae2061f99150ad63f2

**Comment by Anyfc** [comment]
@balonik  Thanks
