### ISSUE TITLE
5.22最新版是不是又改设置了？一片空白

### ISSUE THREAD

**Issue by wgf0330** [ronggang/transmission-web-control#83]
winscp手动覆盖安装的，是我安装方法不对么
![05241](https://cloud.githubusercontent.com/assets/18156721/26381696/2781b740-4059-11e7-9bb3-1c20b0e14c50.png)

**Comment by wgf0330** [comment]
恢复到上一版是可以正常显示的
![05242](https://cloud.githubusercontent.com/assets/18156721/26381732/71580e6e-4059-11e7-954b-dca9f72bec25.png)

**Comment by DarkAlexWang** [comment]
@wgf0330 你把浏览器的cookie清一下，应该就好了。

**Comment by wgf0330** [comment]
嗯，清除之后好了

**Comment by wgf0330** [comment]
赞，这次可以自定义种子显示数量，挂pt就方便多了。
改成每页1000先，呵呵
![05243](https://cloud.githubusercontent.com/assets/18156721/26383892/202bf604-4068-11e7-97f0-84863f1c2e92.png)

**Comment by wgf0330** [comment]
再提个小要求，不知道好不好实现，就是列表栏可以自定义显示，像remote gui 一样可以显示服务器等信息，这样就完美了。
呵呵，一点想法，大神根据情况斟酌。

**Comment by wgf0330** [comment]
补充下为啥想要列表显示服务器信息，主要是因为发布种子一般都会多站发布，以换取上传和保种数量。
所以，有的站出种速度快，就可以把上传带宽倾斜到未出种的站。列表可以看到服务器就直观多了。减少在服务器栏查看比对的多次点击。
如图
![05244](https://cloud.githubusercontent.com/assets/18156721/26385336/6ee82d54-4071-11e7-8024-933db554a93c.png)

**Comment by besteric** [comment]
惊喜的发现 Transmision-web-control 居然更新了，同样遇到了这个问题，查看控制台报错

```
Uncaught SyntaxError: Unexpected token a in JSON at position 2
```

清除 Cookie 正常访问了，感觉这个问题还蛮常见的，作者考虑怎么规避下吧：）

**Comment by zieglar** [comment]
用不了几次就要重置 cookie，能否完善下

**Comment by auanasgheps** [comment]
Hi, I've read the first posts using Google Translate, I do not speak Chinese.
I had the same issue as in the first post (empty page), and old version was working correctly. By deleting cookies I resolved the issue.
Thanks a lot.
