### ISSUE TITLE
WEB Control: 1.1 Beta(20170523): disabled controls are not enabled when ticking the option box

### ISSUE THREAD

**Issue by sandrotosi** [ronggang/transmission-web-control#84]
Hello,
i'm running the latest version of transmission-web-control (it's a git checkout up-to-date) and i noticed that all the options currently disabled, are not enabled once ticking their box. for example

- web control
- click on Config (the gear at the top left)
- tab limit
- i have both max global download and upload currently disabled
-- i want to temporarily enable max global upload, so i tick the box on the left of the label
-- the KB/s control remains disabled so i cant insert the limit i want to set, effectively leaving the option disabled

this applies to all the options where you can enabled them and then you can specify some value.

can you have a look at it quickly? it's a pretty big regression

thanks!

**Comment by balonik** [comment]
@sandrotosi 
thanks for the report, I'll work on a fix.
In the meantime you can use a workaround for the Config options.
- click on the checkbox
- click Save - this will close the Config window
- open the Config again, the input fields will be enabled, you can edit the values and click Save to apply

use similar process to disable

**Comment by sandrotosi** [comment]
ooh thanks @balonik for the workaround, it works indeed!

**Comment by DarkAlexWang** [comment]
Please refer e02c107

**Comment by sandrotosi** [comment]
I can confirm this works, thanks @ronggang !! :)

**Comment by ronggang** [comment]
@sandrotosi You're welcome，It was thanks to @DarkAlexWang 👍  :)

**Comment by sandrotosi** [comment]
then thanks @DarkAlexWang !! :)

**Comment by DarkAlexWang** [comment]
Let's thank @balonik, all I did is merging his modifications.

**Comment by ronggang** [comment]
thanks all guys :)
