### ISSUE TITLE
能否给手机版更新下UI

### ISSUE THREAD

**Issue by dr-zxy0** [ronggang/transmission-web-control#85]
手机版的UI太远古了，希望更新下手机版UI

**Comment by ronggang** [comment]
你好，@dr-zxy0 ，不知你对手机版UI有没有好的建议，或希望改成什么样子？

**Comment by dr-zxy0** [comment]
目前的UI给人的感觉好像停留在ios6时代，没有目前主流的UI风格，这看上去很古老，如果可以的话，希望改成扁平化，或者让他看上去跟上目前的主流

**Comment by ronggang** [comment]
谢谢提议，让我重新规划一下。

**Comment by dr-zxy0** [comment]
新的手机ui，看起来好看多了，但是文字显示还是有些问题，希望优化下
