### ISSUE TITLE
建议新增：列表项目中，建议新增“Tracker服务器”！

### ISSUE THREAD

**Issue by lottelucky** [ronggang/transmission-web-control#86]
列表中，缺少Tracker服务器信息，无法通过PT站进行排序
其实这个功能很重要，对于种子非常多且PT站很多的人来讲，是一个不可或缺的信息栏！
希望开发组的DX尽快加上！

**Comment by lottelucky** [comment]
[https://www.z4a.net/image/snbV0](url)

**Comment by DarkAlexWang** [comment]
@lottelucky 不好意思，我没太明白这么做的意义在什么地方，左面的列表不是已经按照tracker分类了么，点选不同的tracker右面就有对应的种子。为什么一定要按照tracker排序。
如果您有时间，可以再详细说下您的需求。谢谢。

**Comment by lottelucky** [comment]
@DarkAlexWang 感谢您的回复。
在项目中增加tracker分类，确实与左侧“服务器分布”功能有重叠，但我主要是基于以下两个考虑：
1、在PC端显示中，往往有些TX习惯性把左侧信息栏收起，只留种子信息，那此时，如果有TRACKER信息项目可以排序或察看，那会显得比较直观和方便；
2、在手机端，本来屏幕就很局限，在狭小的空间中，显然种子列表中有这个信息，就会更方便地进行筛选和定位
