### ISSUE TITLE
QTransmission x64 安裝路徑

### ISSUE THREAD

**Issue by thomasho18** [ronggang/transmission-web-control#88]
您好,

因為Qnap更新到4.3.3後為64bit版本,所以原本的Transmission已無法使用了,
目前的解決方案為一法國人build的QTransmission ( https://www.forum-nas.fr/viewtopic.php?t=2148 )
此QTransmission才能在4.3.0板之後的QNAP運行...

他的路徑結構和原本官方的Transmission的不同,所以我有嘗試將transmission-web-control copy過去...
但是無法正常運作......

不知道您可以指導一下,該如何更改可以運作?

**Comment by memphisyu** [comment]
1.在github上先下载整个zip包，然后定位到release目录，解压transmission-control-full.tar.gz，得到一个web目录。
2、用winscp登录qnap nas，前往/share/CACHEDEV1_DATA/.qpkg/QTransmission/share/transmission/web目录（这里可以参考下你的qnap配置，应该大同小异，主要是硬盘做raid的问题），手动覆盖原有的文件即可。注意可以将原来的index.html改名为index.original.html，这样可以调用web ui的右上角的“原版UI”功能。
3、因为我在用法国人这一版的时候，发现更换成github版的web control后，第一次进入会出现无法加载设置项目的bug，这样就可以使用“原版UI功能”进入法国人这一版的初始UI界面，修改一两个参数。然后再回到github这一版的页面，既可以正常加载出设置界面。

**Comment by thomasho18** [comment]
我剛剛發現如果我將之前原本Transmission下的trcontrol檔案copy過去/share/CACHEDEV1_DATA/.qpkg/QTransmission/share/transmission/web ,就可以正常使用了!
但是如果下載transmission-control-full.tar.gz,解開再覆蓋過去後,就不能用了!
任何功能都不能用,清單列表也不會出來.......

**Comment by memphisyu** [comment]
确实是cookies的问题，我昨天用新版覆盖安装完也是这个没有任何显示的问题，后来看了下其他issue发现就是清除完cookies就好了。
这个昨天忘了一并和你说，不好意思。

**Comment by ronggang** [comment]
关于cookies问题，下次更新时考虑改成其他方式存储。
