### ISSUE TITLE
favicon有白边，可以改用官方的ico

### ISSUE THREAD

**Issue by Cye3s** [ronggang/transmission-web-control#89]
目前的favicon，有白边，在Firefox的标签页上看比较明显
![wb](https://user-images.githubusercontent.com/2126873/26858441-ca730bf6-4b63-11e7-861f-ca75265ba7d4.png)

/usr/share/transmission/web/images/favicon.ico，无白边
![nwb](https://user-images.githubusercontent.com/2126873/26858440-ca6d4d24-4b63-11e7-8696-67a3d766a35c.png)

**Comment by DarkAlexWang** [comment]
@Cye3s 能麻烦你上传一个美白边的么，我自己换了一个，好像还是有白边。

**Comment by DarkAlexWang** [comment]
@Cye3s 你可以上传个网盘，我可以从网盘下载。谢谢

**Comment by Cye3s** [comment]
链接: https://pan.baidu.com/s/1qYCv8Uo 密码: t3zt
直接从官方的web UI里拿的，替换完可能要Ctrl+F5强制刷新

**Comment by DarkAlexWang** [comment]
好的，多谢，我换一下。
