### ISSUE TITLE
0606的版本，导航树里的图标不能显示

### ISSUE THREAD

**Issue by Cye3s** [ronggang/transmission-web-control#90]
![1](https://user-images.githubusercontent.com/2126873/26866102-47aabaaa-4b92-11e7-80ec-e42fdc63d302.png)
![2](https://user-images.githubusercontent.com/2126873/26866099-46efaa44-4b92-11e7-8a37-4afad9417bb8.png)

网络控制台里显示以下资源404
http://xxx:9091/transmission/web/tr-web-control/style/icons/warning.png
服务器的对应路径下没有该文件

旧版里的资源地址是
http://xxx:9091/transmission/web/tr-web-control/script/easyui/themes/icons/warning.png

应该是icons文件件没一起提交到这里
https://github.com/balonik/transmission-web-control/tree/master/src/tr-web-control/style/icons

**Comment by DarkAlexWang** [comment]
@Cye3s 非常感谢，确实是我没有加icons的文件夹，现在应该好了。

**Comment by Cye3s** [comment]
新的transmission-control-full.tar.gz里两个 html 是0字节
