### ISSUE TITLE
服务器上最新的transmission-control-full.tar.gz，怎么好多文件是零字节的？

### ISSUE THREAD

**Issue by lottelucky** [ronggang/transmission-web-control#91]
@ronggang @DarkAlexWang 
两位老大，昨天的transmission-control-full.tar.gz谁压缩的呀，里面好多文件都是零字节

**Comment by DarkAlexWang** [comment]
@lottelucky 哈哈，是我，我昨天的服务器被一个阿根廷的IP各种狂轰乱炸，硬盘空间都占满了，后来拷贝文件的时候全考成零字节了。。。。我一会儿再更新下

**Comment by DarkAlexWang** [comment]
@lottelucky 现在应该好了，不好意思啊。
