### ISSUE TITLE
Styling issues on iPhone

### ISSUE THREAD

**Issue by Rafkat** [ronggang/transmission-web-control#92]
Hi,

Thanks for the nice skin.

Would you be able to fix the issue with text not during on the screen (not possible to see beginning of the torrent name) and the footer is too much transparent so it's not possible to see the text.

Please see attached screenshot.

Many thanks.

![](http://i.imgur.com/I5CwyiZ.jpg)

**Comment by ronggang** [comment]
Thanks for feedback. About Mobile UI, I'm looking for a more suitable way.
