### ISSUE TITLE
是否可以安装到路由器里面的entware环境里

### ISSUE THREAD

**Issue by jackberry** [ronggang/transmission-web-control#93]
是否可以安装到路由器里面的entware环境里

**Comment by ronggang** [comment]
@jackberry 对于你说的这个我不是很了解，如果是Linux环境，只要你有ssh权限，理论上都可以的，只要你能够找到tr的web所在的目录，将内容复制过去就可以了。

**Comment by wgf0330** [comment]
可以的，去 https://github.com/Entware-ng/Entware-ng 这里源列表查看有tr

**Comment by memphisyu** [comment]
题主用的是华硕梅林固件吧。其实直接复制替换掉entware目录原有的web文件夹即可。

**Comment by DarkAlexWang** [comment]
参照@memphisyu的办法应该可以解决，这个就先关了，有问题可以再开。
