### ISSUE TITLE
移动UI下显示问题

### ISSUE THREAD

**Issue by hxzchina** [ronggang/transmission-web-control#94]
1.任务最左侧的文字不显示
比如任务名字为 末日时在做什么.....，末会被吞掉，只能显示 日时在做什么.....
![image](https://user-images.githubusercontent.com/5526522/27625341-e0dc0118-5c16-11e7-9c82-a52d66e9c051.png)

2.单击任务时，多选框的位置很别扭
![image](https://user-images.githubusercontent.com/5526522/27625423-2749cfb8-5c17-11e7-9364-87da13c38b64.png)

**Comment by ronggang** [comment]
我在找一个更好的方式用于移动UI，不过这几个月还得当奶爸，等暑假过完看看能不能更新；
最近只能先将就一下了。:smile:
