### ISSUE TITLE
哪些文件可以精简？

### ISSUE THREAD

**Issue by zhengxinhn** [ronggang/transmission-web-control#96]
因为路由器空间并不大，想自己精简部分文件。

1、我只想保留简中跟英语，lang文件夹中可以修改 _languages.js ，然后只保留en.js zh-CN.js 。
default.js 跟en.js 都是英语，第一次打开默认好像是简中，default.js是不是可以去掉？

2、/script/easyui 中有theme，但是我好像没找到设置主题的地方。

3、/script/min 中似乎是/script 目录下压缩的文件，script/下的相应文件可以去掉？

4、/script/jquery/mobile 下有1.32 、1.45 2个版本。

**Comment by zhengxinhn** [comment]
删了不少文件，甚至把删了一些移动端相关的。。
好像还是比原版要大不少，主要在/script/easyui里。

**Comment by ronggang** [comment]
嗯，源码下是包含了一些使用环境里不需要的文件，使用环境里只需要当前主题和min下的脚本即可，其他可根据需要自行删除。
