### ISSUE TITLE
Not working with Chrome

### ISSUE THREAD

**Issue by sarkye** [ronggang/transmission-web-control#99]
Buttons and nothing is working with Chrome..
Chrome Version 59.0.3071.115 (Official build) (64-bits)

**Comment by sarkye** [comment]
![knipsel](https://user-images.githubusercontent.com/16682300/28408892-33314558-6d39-11e7-8287-3ccef3d4b580.JPG)

**Comment by shNanChen** [comment]
我也是，清下cookies就能打开，
反复发生，
是不是因为链接中带了用户名和密码？

2017年7月20日 16:50，"sarkye" <notifications@github.com>写道：

**Comment by sarkye** [comment]
Solved, thanks!
